# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Study.delete_all
Analysis.delete_all
Stock.delete_all
Url.delete_all

#Market.delete_all



###Stock###
stock_list = [
  [1, "IT0001233417", "", "A2a", "", nil, "", ""],
  [2, "IT0003506190", "", "Atlantia", "", nil, "", ""],
  [3, "IT0003261697", "", "Azimut Holding", "", nil, "", ""],
  [4, "IT0001031084", "", "Banca Generali", "", nil, "", ""],
  [5, "IT0004776628", "", "Banca Mediolanum", "", nil, "", ""],
  [6, "IT0005218380", "", "Banco Bpm", "", nil, "", ""],
  [7, "IT0000066123", "", "Bper Banca", "", nil, "", ""],
  [8, "IT0005252728", "", "Brembo", "", nil, "", ""],
  [9, "IT0001347308", "", "Buzzi Unicem", "", nil, "", ""],
  [10, "IT0005252207", "", "Campari", "", nil, "", ""],
  [11, "NL0010545661", "", "Cnh Industrial", "", nil, "", ""],
  [12, "IT0003128367", "", "Enel", "", nil, "", ""],
  [13, "IT0003132476", "", "Eni", "", nil, "", ""],  
  [14, "NL0012059018", "", "Exor", "", nil, "", ""],
  [15, "NL0011585146", "", "Ferrari", "", nil, "", ""],
  [16, "NL0010877643", "", "Fiat Chrysler Automobiles", "", nil, "", ""],
  [17, "IT0000072170", "", "Finecobank", "", nil, "", ""],
  [18, "IT0000062072", "", "Generali", "", nil, "", ""],
  [19, "IT0000072618", "", "Intesa Sanpaolo", "", nil, "", ""],
  [20, "IT0005211237", "", "Italgas", "", nil, "", ""],
  [21, "IT0003856405", "", "Leonardo", "", nil, "", ""],
  [22, "IT0001479374", "", "Luxottica", "", nil, "", ""],
  [23, "IT0001063210", "", "Mediaset", "", nil, "", ""],  
  [24, "IT0000062957", "", "Mediobanca", "", nil, "", ""],
  [25, "IT0004965148", "", "Moncler", "", nil, "", ""],
  [26, "IT0003796171", "", "Poste Italiane", "", nil, "", ""],
  [27, "IT0004176001", "", "Prysmian", "", nil, "", ""],
  [28, "IT0003828271", "", "Recordati", "", nil, "", ""],
  [29, "IT0005252140", "", "Saipem", "", nil, "", ""],
  [30, "IT0004712375", "", "Salvatore Ferragamo", "", nil, "", ""],
  [31, "IT0003153415", "", "Snam", "", nil, "", ""],
  [32, "NL0000226223", "", "Stmicroelectronics", "", nil, "", ""],
  [33, "IT0003497168", "", "Telecom Italia", "", nil, "", ""], 
  [34, "LU0156801721", "", "Tenaris", "", nil, "", ""],
  [35, "IT0003242622", "", "Terna - Rete Elettrica Nazionale", "", nil, "", ""],
  [36, "IT0003487029", "", "Ubi Banca", "", nil, "", ""],
  [37, "IT0005239360", "", "Unicredit", "", nil, "", ""],
  [38, "IT0004810054", "", "Unipol", "", nil, "", ""],
  [39, "IT0004827447", "", "Unipolsai", "", nil, "", ""],
  [40, "IT0003540470", "", "Yoox Net-A-Porter Group", "", nil, "", ""],
  
  [41, "IT0001207098", "", "Acea", "", nil, "", ""],
  [42, "IT0001469953", "", "Acotel Group", "", nil, "", ""],
  [43, "IT0001382024", "", "Acsm-Agam", "", nil, "", ""],
  [44, "IT0005065849", "", "Aedes", "", nil, "", ""],
  [45, "IT0001384590", "", "Aeffe", "", nil, "", ""],
  [46, "IT0001006128", "", "Aeroporto Guglielmo Marconi", "", nil, "", ""],
  [47, "IT0004720733", "", "Alerion Cleanpower", "", nil, "", ""],
  [48, "IT0001042297", "", "Ambienthesis", "", nil, "", ""],
  [49, "IT0004056880", "", "Amplifon", "", nil, "", ""],
  [50, "IT0004998065", "", "Anima Holding", "", nil, "", ""],
  [51, "IT0003977540", "", "Ansaldo Sts", "", nil, "", ""],
  [52, "IT0004093263", "", "Ascopiave", "", nil, "", ""],
  [53, "IT0003261069", "", "Astaldi", "", nil, "", ""],
  [54, "IT0000084027", "", "Astm", "", nil, "", ""],
  [55, "IT0001137345", "", "Autogrill", "", nil, "", ""],
  [56, "IT0000084043", "", "Autostrade Meridionali", "", nil, "", ""],
  [57, "IT0005119810", "", "Avio", "", nil, "", ""],
  
  [58, "IT0001268561", "", "B&C Speakers", "", nil, "", ""],
  [59, "IT0005108763", "", "Banca Carige", "", nil, "", ""],
  [60, "IT0005244402", "", "Banca Farmafactoring", "", nil, "", ""],
  [61, "IT0000088853", "", "Banca Finnat", "", nil, "", ""],
  [62, "IT0003188064", "", "Banca Ifis", "", nil, "", ""],
  [63, "IT0000074077", "", "Banca Intermobiliare", "", nil, "", ""],
  [64, "IT0000784196", "", "Banca Pop Sondrio", "", nil, "", ""],
  [65, "IT0001073045", "", "Banca Profilo", "", nil, "", ""],
  [66, "IT0003173629", "", "Banca Sistema", "", nil, "", ""],
  [67, "IT0001041000", "", "Banco Di Desio E Brianza", "", nil, "", ""],
  [68, "IT0001005070", "", "Banco Di Sardegna Rsp", "", nil, "", ""],
  [69, "IT0001033700", "", "Basicnet", "", nil, "", ""],
  [70, "IT0004412497", "", "Bastogi", "", nil, "", ""],
  [71, "IT0001479523", "", "Be", "", nil, "", ""],
  [72, "IT0001223277", "", "Beghelli", "", nil, "", ""],
  [73, "IT0001389631", "", "Beni Stabili", "", nil, "", ""],
  [74, "IT0004273915", "", "Best Union Company", "", nil, "", ""],
  [75, "IT0004222102", "", "Bialetti Industrie", "", nil, "", ""],
  [76, "IT0004095888", "", "Biancamano", "", nil, "", ""],
  [77, "IT0003097257", "", "Biesse", "", nil, "", ""],
  [78, "IT0004711203", "", "Bioera", "", nil, "", ""],
  [79, "IT0000066180", "", "Brioschi", "", nil, "", ""],
  [80, "IT0004764699", "", "Brunello Cucinelli", "", nil, "", ""],
  [81, "IT0001347308", "", "Buzzi Unicem", "", nil, "", ""]

]

stock_list.each do |id, isin, cod, name, sector, last_price, variation, market_phase|
  Stock.create(id: id, isin: isin, cod: cod, name: name, sector: sector, last_price: last_price, variation: variation, market_phase: market_phase)
end
###Stock###



###Url###
url_list = [
  [ "IT0001233417", "http://www.borsaitaliana.it/borsa/azioni/scheda/IT0001233417.html?lang=it", "http://www.borsaitaliana.it/borsa/azioni/analisi-tecnica.html?isin=IT0001233417&lang=it", "http://finanza-mercati.ilsole24ore.com/quotazioni.php?QUOTE=!A2A.MI", "http://finanza-mercati.ilsole24ore.com/fcxp?page=Dettaglio_FTA_Sommario&cmd=framexplane&chId=70&FILTER_VALUE=IT0001233417&Lettera=A&QUOTE=%21A2A.MI", "http://www.soldionline.it/quotazioni/azioni/IT0001233417.html", "https://finanza.repubblica.it/Company/Advanced?symbol=A2A:IM", "https://it.investing.com/equities/a2a-spa", "", "https://www.milanofinanza.it/quotazioni/dettaglio/a2a-2ae00c0", "https://www.milanofinanza.it/mercati/analisi-tecnica?mercato=italiano&stockcodert=00c0&codicestrumento=w2ae&DBCOD=A2A"],
  [ "IT0003506190", "http://www.borsaitaliana.it/borsa/azioni/scheda/IT0003506190.html?lang=it", "http://www.borsaitaliana.it/borsa/azioni/analisi-tecnica.html?isin=IT0003506190&lang=it", "http://finanza-mercati.ilsole24ore.com/quotazioni.php?QUOTE=!ATL.MI", "http://finanza-mercati.ilsole24ore.com/fcxp?page=Dettaglio_FTA_Sommario&cmd=framexplane&chId=70&FILTER_VALUE=IT0003506190&Lettera=A&QUOTE=%21ATL.MI", "http://www.soldionline.it/quotazioni/azioni/IT0003506190.html", "https://finanza.repubblica.it/Company/Advanced?symbol=ATL:IM", "https://it.investing.com/equities/atlantia", "", "https://www.milanofinanza.it/quotazioni/dettaglio/atlantia-2ae003b", "https://www.milanofinanza.it/mercati/analisi-tecnica?mercato=italiano&stockcodert=003b&codicestrumento=w2ae&DBCOD=ATL"],
  [ "IT0003261697", "http://www.borsaitaliana.it/borsa/azioni/scheda/IT0003261697.html?lang=it", "http://www.borsaitaliana.it/borsa/azioni/analisi-tecnica.html?isin=IT0003261697&lang=it", "http://finanza-mercati.ilsole24ore.com/quotazioni.php?QUOTE=!AZM.MI", "http://finanza-mercati.ilsole24ore.com/fcxp?page=Dettaglio_FTA_Sommario&cmd=framexplane&chId=70&FILTER_VALUE=IT0003261697&Lettera=A&QUOTE=%21AZM.MI", "http://www.soldionline.it/quotazioni/azioni/IT0003261697.html", "https://finanza.repubblica.it/Company/Advanced?symbol=AZM:IM", "https://it.investing.com/equities/azimut-holding", "", "https://www.milanofinanza.it/quotazioni/dettaglio/azimut-2ae03ba", "https://www.milanofinanza.it/mercati/analisi-tecnica?mercato=italiano&stockcodert=03ba&codicestrumento=w2ae&DBCOD=AZM"],
  [ "IT0001031084", "http://www.borsaitaliana.it/borsa/azioni/scheda/IT0001031084.html?lang=it", "http://www.borsaitaliana.it/borsa/azioni/analisi-tecnica.html?isin=IT0001031084&lang=it", "http://finanza-mercati.ilsole24ore.com/quotazioni.php?QUOTE=!BGN.MI", "http://finanza-mercati.ilsole24ore.com/fcxp?page=Dettaglio_FTA_Sommario&cmd=framexplane&chId=70&FILTER_VALUE=IT0001031084&Lettera=B&QUOTE=%21BGN.MI", "http://www.soldionline.it/quotazioni/azioni/IT0001031084.html", "https://finanza.repubblica.it/Company/Advanced?symbol=BGN:IM", "https://it.investing.com/equities/banca-generali", "", "https://www.milanofinanza.it/quotazioni/dettaglio/banca-generali-2ae0405", "https://www.milanofinanza.it/mercati/analisi-tecnica?mercato=italiano&stockcodert=0405&codicestrumento=w2ae&DBCOD=BGN"],
  [ "IT0004776628", "http://www.borsaitaliana.it/borsa/azioni/scheda/IT0004776628.html?lang=it", "http://www.borsaitaliana.it/borsa/azioni/analisi-tecnica.html?isin=IT0004776628&lang=it", "http://finanza-mercati.ilsole24ore.com/quotazioni.php?QUOTE=!BMED.MI", "http://finanza-mercati.ilsole24ore.com/fcxp?page=Dettaglio_FTA_Sommario&cmd=framexplane&chId=70&FILTER_VALUE=IT0004776628&Lettera=B&QUOTE=%21BMED.MI", "http://www.soldionline.it/quotazioni/azioni/IT0004776628.html", "https://finanza.repubblica.it/Company/Advanced?symbol=BMED:IM", "https://it.investing.com/equities/mediolanum", "", "https://www.milanofinanza.it/quotazioni/dettaglio/banca-mediolanum-2ae106c", "https://www.milanofinanza.it/mercati/analisi-tecnica?mercato=italiano&stockcodert=106c&codicestrumento=w2ae&DBCOD=BMED"],
  [ "IT0005218380", "http://www.borsaitaliana.it/borsa/azioni/scheda/IT0005218380.html?lang=it", "http://www.borsaitaliana.it/borsa/azioni/analisi-tecnica.html?isin=IT0005218380&lang=it", "http://finanza-mercati.ilsole24ore.com/quotazioni.php?QUOTE=!BAMI.MI", "http://finanza-mercati.ilsole24ore.com/fcxp?page=Dettaglio_FTA_Sommario&cmd=framexplane&chId=70&FILTER_VALUE=IT0005218380&Lettera=B&QUOTE=%21BAMI.MI", "http://www.soldionline.it/quotazioni/azioni/IT0005218380.html", "https://finanza.repubblica.it/Company/Advanced?symbol=BAMI:IM", "https://it.investing.com/equities/banco-popolare", "", "https://www.milanofinanza.it/quotazioni/dettaglio/banco-bpm-2ae10a2", "https://www.milanofinanza.it/mercati/analisi-tecnica?mercato=italiano&stockcodert=10a2&codicestrumento=w2ae&DBCOD=BAMI"],
  [ "IT0000066123", "http://www.borsaitaliana.it/borsa/azioni/scheda/IT0000066123.html?lang=it", "http://www.borsaitaliana.it/borsa/azioni/analisi-tecnica.html?isin=IT0000066123&lang=it", "http://finanza-mercati.ilsole24ore.com/quotazioni.php?QUOTE=!BPE.MI", "http://finanza-mercati.ilsole24ore.com/fcxp?page=Dettaglio_FTA_Sommario&cmd=framexplane&chId=70&FILTER_VALUE=IT0000066123&Lettera=B&QUOTE=%21BPE.MI", "http://www.soldionline.it/quotazioni/azioni/IT0000066123.html", "https://finanza.repubblica.it/Company/Advanced?symbol=BPE:IM", "https://it.investing.com/equities/banca-popolare-dell-emilia", "", "https://www.milanofinanza.it/quotazioni/dettaglio/bper-banca-2ae006e", "https://www.milanofinanza.it/mercati/analisi-tecnica?mercato=italiano&stockcodert=006e&codicestrumento=w2ae&DBCOD=BPE"],
  [ "IT0005252728", "http://www.borsaitaliana.it/borsa/azioni/scheda/IT0005252728.html?lang=it", "http://www.borsaitaliana.it/borsa/azioni/analisi-tecnica.html?isin=IT0005252728&lang=it", "http://finanza-mercati.ilsole24ore.com/quotazioni.php?QUOTE=!BRE.MI", "http://finanza-mercati.ilsole24ore.com/fcxp?page=Dettaglio_FTA_Sommario&cmd=framexplane&chId=70&FILTER_VALUE=IT0005252728&Lettera=B&QUOTE=%21BRE.MI", "http://www.soldionline.it/quotazioni/azioni/IT0005252728.html", "https://finanza.repubblica.it/Company/Advanced?symbol=BRE:IM", "https://it.investing.com/equities/brembo", "", "https://www.milanofinanza.it/quotazioni/dettaglio/brembo-2ae000c", "https://www.milanofinanza.it/mercati/analisi-tecnica?mercato=italiano&stockcodert=000c&codicestrumento=w2ae&DBCOD=BRE"],
  [ "IT0001347308", "http://www.borsaitaliana.it/borsa/azioni/scheda/IT0001347308.html?lang=it", "http://www.borsaitaliana.it/borsa/azioni/analisi-tecnica.html?isin=IT0001347308&lang=it", "http://finanza-mercati.ilsole24ore.com/quotazioni.php?QUOTE=!BZU.MI", "http://finanza-mercati.ilsole24ore.com/fcxp?page=Dettaglio_FTA_Sommario&cmd=framexplane&chId=70&FILTER_VALUE=IT0001347308&Lettera=B&QUOTE=%21BZU.MI", "http://www.soldionline.it/quotazioni/azioni/IT0001347308.html", "https://finanza.repubblica.it/Company/Advanced?symbol=BZU:IM", "https://it.investing.com/equities/buzzi-unicem", "", "https://www.milanofinanza.it/quotazioni/dettaglio/buzzi-unicem-2ae0013", "https://www.milanofinanza.it/mercati/analisi-tecnica?mercato=italiano&stockcodert=0013&codicestrumento=w2ae&DBCOD=BZU"],
  [ "IT0005252207", "http://www.borsaitaliana.it/borsa/azioni/scheda/IT0005252207.html?lang=it", "http://www.borsaitaliana.it/borsa/azioni/analisi-tecnica.html?isin=IT0005252207&lang=it", "http://finanza-mercati.ilsole24ore.com/quotazioni.php?QUOTE=!CPR.MI", "http://finanza-mercati.ilsole24ore.com/fcxp?page=Dettaglio_FTA_Sommario&cmd=framexplane&chId=70&FILTER_VALUE=IT0005252207&Lettera=C&QUOTE=%21CPR.MI", "http://www.soldionline.it/quotazioni/azioni/IT0005252207.html", "https://finanza.repubblica.it/Company/Advanced?symbol=CPR:IM", "https://it.investing.com/equities/campari", "", "https://www.milanofinanza.it/quotazioni/dettaglio/campari-2ae01f2", "https://www.milanofinanza.it/mercati/analisi-tecnica?mercato=italiano&stockcodert=01f2&codicestrumento=w2ae&DBCOD=CPR"],
  [ "NL0010545661", "http://www.borsaitaliana.it/borsa/azioni/scheda/NL0010545661.html?lang=it", "http://www.borsaitaliana.it/borsa/azioni/analisi-tecnica.html?isin=NL0010545661&lang=it", "http://finanza-mercati.ilsole24ore.com/quotazioni.php?QUOTE=!CNHI.MI", "http://finanza-mercati.ilsole24ore.com/fcxp?page=Dettaglio_FTA_Sommario&cmd=framexplane&chId=70&FILTER_VALUE=NL0010545661&Lettera=C&QUOTE=%21CNHI.MI", "http://www.soldionline.it/quotazioni/azioni/NL0010545661.html", "https://finanza.repubblica.it/Company/Advanced?symbol=CNHI:IM", "https://it.investing.com/equities/cnh-industral-nv?cid=42603", "", "https://www.milanofinanza.it/quotazioni/dettaglio/cnh-industrial-2ae1025", "https://www.milanofinanza.it/mercati/analisi-tecnica?mercato=italiano&stockcodert=1025&codicestrumento=w2ae&DBCOD=CNHI"],
  [ "IT0003128367", "http://www.borsaitaliana.it/borsa/azioni/scheda/IT0003128367.html?lang=it", "http://www.borsaitaliana.it/borsa/azioni/analisi-tecnica.html?isin=IT0003128367&lang=it", "http://finanza-mercati.ilsole24ore.com/quotazioni.php?QUOTE=!ENEL.MI", "http://finanza-mercati.ilsole24ore.com/fcxp?page=Dettaglio_FTA_Sommario&cmd=framexplane&chId=70&FILTER_VALUE=IT0003128367&Lettera=E&QUOTE=%21ENEL.MI", "http://www.soldionline.it/quotazioni/azioni/IT0003128367.html", "https://finanza.repubblica.it/Company/Advanced?symbol=ENEL:IM", "https://it.investing.com/equities/enel", "", "https://www.milanofinanza.it/quotazioni/dettaglio/enel-2ae008b", "https://www.milanofinanza.it/mercati/analisi-tecnica?mercato=italiano&stockcodert=008b&codicestrumento=w2ae&DBCOD=ENEL"],
  [ "IT0003132476", "http://www.borsaitaliana.it/borsa/azioni/scheda/IT0003132476.html?lang=it", "http://www.borsaitaliana.it/borsa/azioni/analisi-tecnica.html?isin=IT0003132476&lang=it", "http://finanza-mercati.ilsole24ore.com/quotazioni.php?QUOTE=!ENI.MI", "http://finanza-mercati.ilsole24ore.com/fcxp?page=Dettaglio_FTA_Sommario&cmd=framexplane&chId=70&FILTER_VALUE=IT0003132476&Lettera=E&QUOTE=%21ENI.MI", "http://www.soldionline.it/quotazioni/azioni/IT0003132476.html", "https://finanza.repubblica.it/Company/Advanced?symbol=ENI:IM", "https://it.investing.com/equities/eni", "", "https://www.milanofinanza.it/quotazioni/dettaglio/eni-2ae0017", "https://www.milanofinanza.it/mercati/analisi-tecnica?mercato=italiano&stockcodert=0017&codicestrumento=w2ae&DBCOD=ENI"],
  [ "NL0012059018", "http://www.borsaitaliana.it/borsa/azioni/scheda/NL0012059018.html?lang=it", "http://www.borsaitaliana.it/borsa/azioni/analisi-tecnica.html?isin=NL0012059018&lang=it", "http://finanza-mercati.ilsole24ore.com/quotazioni.php?QUOTE=!EXO.MI", "http://finanza-mercati.ilsole24ore.com/fcxp?page=Dettaglio_FTA_Sommario&cmd=framexplane&chId=70&FILTER_VALUE=NL0012059018&Lettera=E&QUOTE=%21EXO.MI", "http://www.soldionline.it/quotazioni/azioni/NL0012059018.html", "https://finanza.repubblica.it/Company/Advanced?symbol=EXO:IM", "https://it.investing.com/equities/exor", "", "https://www.milanofinanza.it/quotazioni/dettaglio/exor-2ae010d", "https://www.milanofinanza.it/mercati/analisi-tecnica?mercato=italiano&stockcodert=010d&codicestrumento=w2ae&DBCOD=EXO"],
  [ "NL0011585146", "http://www.borsaitaliana.it/borsa/azioni/scheda/NL0011585146.html?lang=it", "http://www.borsaitaliana.it/borsa/azioni/analisi-tecnica.html?isin=NL0011585146&lang=it", "http://finanza-mercati.ilsole24ore.com/quotazioni.php?QUOTE=!RACE.MI", "http://finanza-mercati.ilsole24ore.com/fcxp?page=Dettaglio_FTA_Sommario&cmd=framexplane&chId=70&FILTER_VALUE=NL0011585146&Lettera=F&QUOTE=%21RACE.MI", "http://www.soldionline.it/quotazioni/azioni/NL0011585146.html", "https://finanza.repubblica.it/Company/Advanced?symbol=RACE:IM", "https://it.investing.com/equities/ferrari-nv?cid=962346", "", "https://www.milanofinanza.it/quotazioni/dettaglio/ferrari-2ae106d", "https://www.milanofinanza.it/mercati/analisi-tecnica?mercato=italiano&stockcodert=106d&codicestrumento=w2ae&DBCOD=RACE"],
  [ "NL0010877643", "http://www.borsaitaliana.it/borsa/azioni/scheda/NL0010877643.html?lang=it", "http://www.borsaitaliana.it/borsa/azioni/analisi-tecnica.html?isin=NL0010877643&lang=it", "http://finanza-mercati.ilsole24ore.com/quotazioni.php?QUOTE=!FCA.MI", "http://finanza-mercati.ilsole24ore.com/fcxp?page=Dettaglio_FTA_Sommario&cmd=framexplane&chId=70&FILTER_VALUE=NL0010877643&Lettera=F&QUOTE=%21FCA.MI", "http://www.soldionline.it/quotazioni/azioni/NL0010877643.html", "https://finanza.repubblica.it/Company/Advanced?symbol=FCA:IM", "https://it.investing.com/equities/fiat", "", "https://www.milanofinanza.it/quotazioni/dettaglio/fiat-chrysler-automobiles-2ae00be", "https://www.milanofinanza.it/mercati/analisi-tecnica?mercato=italiano&stockcodert=00be&codicestrumento=w2ae&DBCOD=FCA"],
  [ "IT0000072170", "http://www.borsaitaliana.it/borsa/azioni/scheda/IT0000072170.html?lang=it", "http://www.borsaitaliana.it/borsa/azioni/analisi-tecnica.html?isin=IT0000072170&lang=it", "http://finanza-mercati.ilsole24ore.com/quotazioni.php?QUOTE=!FBK.MI", "http://finanza-mercati.ilsole24ore.com/fcxp?page=Dettaglio_FTA_Sommario&cmd=framexplane&chId=70&FILTER_VALUE=IT0000072170&Lettera=F&QUOTE=%21FBK.MI", "http://www.soldionline.it/quotazioni/azioni/IT0000072170.html", "https://finanza.repubblica.it/Company/Advanced?symbol=FBK:IM", "https://it.investing.com/equities/finecobank-banca-fineco-spa", "", "https://www.milanofinanza.it/quotazioni/dettaglio/finecobank-2ae103d", "https://www.milanofinanza.it/mercati/analisi-tecnica?mercato=italiano&stockcodert=103d&codicestrumento=w2ae&DBCOD=FBK"],
  [ "IT0000062072", "http://www.borsaitaliana.it/borsa/azioni/scheda/IT0000062072.html?lang=it", "http://www.borsaitaliana.it/borsa/azioni/analisi-tecnica.html?isin=IT0000062072&lang=it", "http://finanza-mercati.ilsole24ore.com/quotazioni.php?QUOTE=!G.MI", "http://finanza-mercati.ilsole24ore.com/fcxp?page=Dettaglio_FTA_Sommario&cmd=framexplane&chId=70&FILTER_VALUE=IT0000062072&Lettera=G&QUOTE=%21G.MI", "http://www.soldionline.it/quotazioni/azioni/IT0000062072.html", "https://finanza.repubblica.it/Company/Advanced?symbol=G:IM", "https://it.investing.com/equities/generali-ass", "", "https://www.milanofinanza.it/quotazioni/dettaglio/generali-ass-2ae00e5", "https://www.milanofinanza.it/mercati/analisi-tecnica?mercato=italiano&stockcodert=00e5&codicestrumento=w2ae&DBCOD=G"],
  [ "IT0000072618", "http://www.borsaitaliana.it/borsa/azioni/scheda/IT0000072618.html?lang=it", "http://www.borsaitaliana.it/borsa/azioni/analisi-tecnica.html?isin=IT0000072618&lang=it", "http://finanza-mercati.ilsole24ore.com/quotazioni.php?QUOTE=!ISP.MI", "http://finanza-mercati.ilsole24ore.com/fcxp?page=Dettaglio_FTA_Sommario&cmd=framexplane&chId=70&FILTER_VALUE=IT0000072618&Lettera=I&QUOTE=%21ISP.MI", "http://www.soldionline.it/quotazioni/azioni/IT0000072618.html", "https://finanza.repubblica.it/Company/Advanced?symbol=ISP:IM", "https://it.investing.com/equities/intesa-sanpaolo", "", "https://www.milanofinanza.it/quotazioni/dettaglio/intesa-sanpaolo-2ae0056", "https://www.milanofinanza.it/mercati/analisi-tecnica?mercato=italiano&stockcodert=0056&codicestrumento=w2ae&DBCOD=ISP"],
  [ "IT0005211237", "http://www.borsaitaliana.it/borsa/azioni/scheda/IT0005211237.html?lang=it", "http://www.borsaitaliana.it/borsa/azioni/analisi-tecnica.html?isin=IT0005211237&lang=it", "http://finanza-mercati.ilsole24ore.com/quotazioni.php?QUOTE=!IG.MI", "http://finanza-mercati.ilsole24ore.com/fcxp?page=Dettaglio_FTA_Sommario&cmd=framexplane&chId=70&FILTER_VALUE=IT0005211237&Lettera=I&QUOTE=%21IG.MI", "http://www.soldionline.it/quotazioni/azioni/IT0005211237.html", "https://finanza.repubblica.it/Company/Advanced?symbol=IG:IM", "https://it.investing.com/equities/italgas-spa", "", "https://www.milanofinanza.it/quotazioni/dettaglio/italgas-2ae109f", "https://www.milanofinanza.it/mercati/analisi-tecnica?mercato=italiano&stockcodert=109f&codicestrumento=w2ae&DBCOD=IG"],
  [ "IT0003856405", "http://www.borsaitaliana.it/borsa/azioni/scheda/IT0003856405.html?lang=it", "http://www.borsaitaliana.it/borsa/azioni/analisi-tecnica.html?isin=IT0003856405&lang=it", "http://finanza-mercati.ilsole24ore.com/quotazioni.php?QUOTE=!LDO.MI", "http://finanza-mercati.ilsole24ore.com/fcxp?page=Dettaglio_FTA_Sommario&cmd=framexplane&chId=70&FILTER_VALUE=IT0003856405&Lettera=L&QUOTE=%21LDO.MI", "http://www.soldionline.it/quotazioni/azioni/IT0003856405.html", "https://finanza.repubblica.it/Company/Advanced?symbol=LDO:IM", "https://it.investing.com/equities/finmeccanica", "", "https://www.milanofinanza.it/quotazioni/dettaglio/leonardo-2ae00b2", "https://www.milanofinanza.it/mercati/analisi-tecnica?mercato=italiano&stockcodert=00b2&codicestrumento=w2ae&DBCOD=LDO"],
  [ "IT0001479374", "http://www.borsaitaliana.it/borsa/azioni/scheda/IT0001479374.html?lang=it", "http://www.borsaitaliana.it/borsa/azioni/analisi-tecnica.html?isin=IT0001479374&lang=it", "http://finanza-mercati.ilsole24ore.com/quotazioni.php?QUOTE=!LUX.MI", "http://finanza-mercati.ilsole24ore.com/fcxp?page=Dettaglio_FTA_Sommario&cmd=framexplane&chId=70&FILTER_VALUE=IT0001479374&Lettera=L&QUOTE=%21LUX.MI", "http://www.soldionline.it/quotazioni/azioni/IT0001479374.html", "https://finanza.repubblica.it/Company/Advanced?symbol=LUX:IM", "https://it.investing.com/equities/luxottica", "", "https://www.milanofinanza.it/quotazioni/dettaglio/luxottica-group-2ae01c1", "https://www.milanofinanza.it/mercati/analisi-tecnica?mercato=italiano&stockcodert=01c1&codicestrumento=w2ae&DBCOD=LUX"],
  [ "IT0001063210", "http://www.borsaitaliana.it/borsa/azioni/scheda/IT0001063210.html?lang=it", "http://www.borsaitaliana.it/borsa/azioni/analisi-tecnica.html?isin=IT0001063210&lang=it", "http://finanza-mercati.ilsole24ore.com/quotazioni.php?QUOTE=!MS.MI", "http://finanza-mercati.ilsole24ore.com/fcxp?page=Dettaglio_FTA_Sommario&cmd=framexplane&chId=70&FILTER_VALUE=IT0001063210&Lettera=M&QUOTE=%21MS.MI", "http://www.soldionline.it/quotazioni/azioni/IT0001063210.html", "https://finanza.repubblica.it/Company/Advanced?symbol=MS:IM", "https://it.investing.com/equities/mediaset", "", "https://www.milanofinanza.it/quotazioni/dettaglio/mediaset-s-p-a-2ae0029", "https://www.milanofinanza.it/mercati/analisi-tecnica?mercato=italiano&stockcodert=0029&codicestrumento=w2ae&DBCOD=MS"],
  [ "IT0000062957", "http://www.borsaitaliana.it/borsa/azioni/scheda/IT0000062957.html?lang=it", "http://www.borsaitaliana.it/borsa/azioni/analisi-tecnica.html?isin=IT0000062957&lang=it", "http://finanza-mercati.ilsole24ore.com/quotazioni.php?QUOTE=!MB.MI", "http://finanza-mercati.ilsole24ore.com/fcxp?page=Dettaglio_FTA_Sommario&cmd=framexplane&chId=70&FILTER_VALUE=IT0000062957&Lettera=M&QUOTE=%21MB.MI", "http://www.soldionline.it/quotazioni/azioni/IT0000062957.html", "https://finanza.repubblica.it/Company/Advanced?symbol=MB:IM", "https://it.investing.com/equities/mediobanca", "", "https://www.milanofinanza.it/quotazioni/dettaglio/mediobanca-2ae011d", "https://www.milanofinanza.it/mercati/analisi-tecnica?mercato=italiano&stockcodert=011d&codicestrumento=w2ae&DBCOD=MB"],
  [ "IT0004965148", "http://www.borsaitaliana.it/borsa/azioni/scheda/IT0004965148.html?lang=it", "http://www.borsaitaliana.it/borsa/azioni/analisi-tecnica.html?isin=IT0004965148&lang=it", "http://finanza-mercati.ilsole24ore.com/quotazioni.php?QUOTE=!MONC.MI", "http://finanza-mercati.ilsole24ore.com/fcxp?page=Dettaglio_FTA_Sommario&cmd=framexplane&chId=70&FILTER_VALUE=IT0004965148&Lettera=M&QUOTE=%21MONC.MI", "http://www.soldionline.it/quotazioni/azioni/IT0004965148.html", "https://finanza.repubblica.it/Company/Advanced?symbol=MONC:IM", "https://it.investing.com/equities/moncler-spa", "", "https://www.milanofinanza.it/quotazioni/dettaglio/moncler-2ae1029", "https://www.milanofinanza.it/mercati/analisi-tecnica?mercato=italiano&stockcodert=1029&codicestrumento=w2ae&DBCOD=MONC"],
  [ "IT0003796171", "http://www.borsaitaliana.it/borsa/azioni/scheda/IT0003796171.html?lang=it", "http://www.borsaitaliana.it/borsa/azioni/analisi-tecnica.html?isin=IT0003796171&lang=it", "http://finanza-mercati.ilsole24ore.com/quotazioni.php?QUOTE=!PST.MI", "http://finanza-mercati.ilsole24ore.com/fcxp?page=Dettaglio_FTA_Sommario&cmd=framexplane&chId=70&FILTER_VALUE=IT0003796171&Lettera=P&QUOTE=%21PST.MI", "http://www.soldionline.it/quotazioni/azioni/IT0003796171.html", "https://finanza.repubblica.it/Company/Advanced?symbol=PST:IM", "https://it.investing.com/equities/poste-italiane-spa", "", "https://www.milanofinanza.it/quotazioni/dettaglio/poste-italiane-2ae1064", "https://www.milanofinanza.it/mercati/analisi-tecnica?mercato=italiano&stockcodert=1064&codicestrumento=w2ae&DBCOD=PST"],
  [ "IT0004176001", "http://www.borsaitaliana.it/borsa/azioni/scheda/IT0004176001.html?lang=it", "http://www.borsaitaliana.it/borsa/azioni/analisi-tecnica.html?isin=IT0004176001&lang=it", "http://finanza-mercati.ilsole24ore.com/quotazioni.php?QUOTE=!PRY.MI", "http://finanza-mercati.ilsole24ore.com/fcxp?page=Dettaglio_FTA_Sommario&cmd=framexplane&chId=70&FILTER_VALUE=IT0004176001&Lettera=P&QUOTE=%21PRY.MI", "http://www.soldionline.it/quotazioni/azioni/IT0004176001.html", "https://finanza.repubblica.it/Company/Advanced?symbol=PRY:IM", "https://it.investing.com/equities/prysmian", "", "https://www.milanofinanza.it/quotazioni/dettaglio/prysmian-2ae041e", "https://www.milanofinanza.it/mercati/analisi-tecnica?mercato=italiano&stockcodert=041e&codicestrumento=w2ae&DBCOD=PRY"],
  [ "IT0003828271", "http://www.borsaitaliana.it/borsa/azioni/scheda/IT0003828271.html?lang=it", "http://www.borsaitaliana.it/borsa/azioni/analisi-tecnica.html?isin=IT0003828271&lang=it", "http://finanza-mercati.ilsole24ore.com/quotazioni.php?QUOTE=!REC.MI", "http://finanza-mercati.ilsole24ore.com/fcxp?page=Dettaglio_FTA_Sommario&cmd=framexplane&chId=70&FILTER_VALUE=IT0003828271&Lettera=P&QUOTE=%21REC.MI", "http://www.soldionline.it/quotazioni/azioni/IT0003828271.html", "https://finanza.repubblica.it/Company/Advanced?symbol=REC:IM", "https://it.investing.com/equities/recordati", "", "https://www.milanofinanza.it/quotazioni/dettaglio/recordati-ord-2ae01cd", "https://www.milanofinanza.it/mercati/analisi-tecnica?mercato=italiano&stockcodert=01cd&codicestrumento=w2ae&DBCOD=REC"],
  [ "IT0005252140", "http://www.borsaitaliana.it/borsa/azioni/scheda/IT0005252140.html?lang=it", "http://www.borsaitaliana.it/borsa/azioni/analisi-tecnica.html?isin=IT0005252140&lang=it", "http://finanza-mercati.ilsole24ore.com/quotazioni.php?QUOTE=!SPM.MI", "http://finanza-mercati.ilsole24ore.com/fcxp?page=Dettaglio_FTA_Sommario&cmd=framexplane&chId=70&FILTER_VALUE=IT0005252140&Lettera=S&QUOTE=%21SPM.MI", "http://www.soldionline.it/quotazioni/azioni/IT0005252140.html", "https://finanza.repubblica.it/Company/Advanced?symbol=SPM:IM", "https://it.investing.com/equities/saipem", "", "https://www.milanofinanza.it/quotazioni/dettaglio/saipem-2ae0193", "https://www.milanofinanza.it/mercati/analisi-tecnica?mercato=italiano&stockcodert=0193&codicestrumento=w2ae&DBCOD=SPM"],
  [ "IT0004712375", "http://www.borsaitaliana.it/borsa/azioni/scheda/IT0004712375.html?lang=it", "http://www.borsaitaliana.it/borsa/azioni/analisi-tecnica.html?isin=IT0004712375&lang=it", "http://finanza-mercati.ilsole24ore.com/quotazioni.php?QUOTE=!SFER.MI", "http://finanza-mercati.ilsole24ore.com/fcxp?page=Dettaglio_FTA_Sommario&cmd=framexplane&chId=70&FILTER_VALUE=IT0004712375&Lettera=S&QUOTE=%21SFER.MI", "http://www.soldionline.it/quotazioni/azioni/IT0004712375.html", "https://finanza.repubblica.it/Company/Advanced?symbol=SFER:IM", "https://it.investing.com/equities/salvatore-ferragamo-italia-spa", "", "https://www.milanofinanza.it/quotazioni/dettaglio/salvatore-ferragamo-2ae0049", "https://www.milanofinanza.it/mercati/analisi-tecnica?mercato=italiano&stockcodert=0049&codicestrumento=w2ae&DBCOD=SFER"],
  [ "IT0003153415", "http://www.borsaitaliana.it/borsa/azioni/scheda/IT0003153415.html?lang=it", "http://www.borsaitaliana.it/borsa/azioni/analisi-tecnica.html?isin=IT0003153415&lang=it", "http://finanza-mercati.ilsole24ore.com/quotazioni.php?QUOTE=!SRG.MI", "http://finanza-mercati.ilsole24ore.com/fcxp?page=Dettaglio_FTA_Sommario&cmd=framexplane&chId=70&FILTER_VALUE=IT0003153415&Lettera=S&QUOTE=%21SRG.MI", "http://www.soldionline.it/quotazioni/azioni/IT0003153415.html", "https://finanza.repubblica.it/Company/Advanced?symbol=SRG:IM", "https://it.investing.com/equities/snam-rete-gas", "", "https://www.milanofinanza.it/quotazioni/dettaglio/snam-2ae0363", "https://www.milanofinanza.it/mercati/analisi-tecnica?mercato=italiano&stockcodert=0363&codicestrumento=w2ae&DBCOD=SRG"],
  [ "NL0000226223", "http://www.borsaitaliana.it/borsa/azioni/scheda/NL0000226223.html?lang=it", "http://www.borsaitaliana.it/borsa/azioni/analisi-tecnica.html?isin=NL0000226223&lang=it", "http://finanza-mercati.ilsole24ore.com/quotazioni.php?QUOTE=!STM.MI", "http://finanza-mercati.ilsole24ore.com/fcxp?page=Dettaglio_FTA_Sommario&cmd=framexplane&chId=70&FILTER_VALUE=NL0000226223&Lettera=S&QUOTE=%21STM.MI", "http://www.soldionline.it/quotazioni/azioni/NL0000226223.html", "https://finanza.repubblica.it/Company/Advanced?symbol=STM:IM", "https://it.investing.com/equities/stmicroelectroni?cid=22185", "", "https://www.milanofinanza.it/quotazioni/dettaglio/stmicroelectronics-2ae0022", "https://www.milanofinanza.it/mercati/analisi-tecnica?mercato=italiano&stockcodert=0022&codicestrumento=w2ae&DBCOD=STM"],
  [ "IT0003497168", "http://www.borsaitaliana.it/borsa/azioni/scheda/IT0003497168.html?lang=it", "http://www.borsaitaliana.it/borsa/azioni/analisi-tecnica.html?isin=IT0003497168&lang=it", "http://finanza-mercati.ilsole24ore.com/quotazioni.php?QUOTE=!TIT.MI", "http://finanza-mercati.ilsole24ore.com/fcxp?page=Dettaglio_FTA_Sommario&cmd=framexplane&chId=70&FILTER_VALUE=IT0003497168&Lettera=T&QUOTE=%21TIT.MI", "http://www.soldionline.it/quotazioni/azioni/IT0003497168.html", "https://finanza.repubblica.it/Company/Advanced?symbol=TIT:IM", "https://it.investing.com/equities/telecom-italia", "", "https://www.milanofinanza.it/quotazioni/dettaglio/telecom-italia-2ae0098", "https://www.milanofinanza.it/mercati/analisi-tecnica?mercato=italiano&stockcodert=0098&codicestrumento=w2ae&DBCOD=TIT"], 
  [ "LU0156801721", "http://www.borsaitaliana.it/borsa/azioni/scheda/LU0156801721.html?lang=it", "http://www.borsaitaliana.it/borsa/azioni/analisi-tecnica.html?isin=LU0156801721&lang=it", "http://finanza-mercati.ilsole24ore.com/quotazioni.php?QUOTE=!TEN.MI", "http://finanza-mercati.ilsole24ore.com/fcxp?page=Dettaglio_FTA_Sommario&cmd=framexplane&chId=70&FILTER_VALUE=LU0156801721&Lettera=T&QUOTE=%21TEN.MI", "http://www.soldionline.it/quotazioni/azioni/LU0156801721.html", "https://finanza.repubblica.it/Company/Advanced?symbol=TEN:IM", "https://it.investing.com/equities/tenaris", "", "https://www.milanofinanza.it/quotazioni/dettaglio/tenaris-2ae0383", "https://www.milanofinanza.it/mercati/analisi-tecnica?mercato=italiano&stockcodert=0383&codicestrumento=w2ae&DBCOD=TEN"],
  [ "IT0003242622", "http://www.borsaitaliana.it/borsa/azioni/scheda/IT0003242622.html?lang=it", "http://www.borsaitaliana.it/borsa/azioni/analisi-tecnica.html?isin=IT0003242622&lang=it", "http://finanza-mercati.ilsole24ore.com/quotazioni.php?QUOTE=!TRN.MI", "http://finanza-mercati.ilsole24ore.com/fcxp?page=Dettaglio_FTA_Sommario&cmd=framexplane&chId=70&FILTER_VALUE=IT0003242622&Lettera=T&QUOTE=%21TRN.MI", "http://www.soldionline.it/quotazioni/azioni/IT0003242622.html", "https://finanza.repubblica.it/Company/Advanced?symbol=TRN:IM", "https://it.investing.com/equities/terna", "", "https://www.milanofinanza.it/quotazioni/dettaglio/terna-2ae03b7", "https://www.milanofinanza.it/mercati/analisi-tecnica?mercato=italiano&stockcodert=03b7&codicestrumento=w2ae&DBCOD=TRN"],
  [ "IT0003487029", "http://www.borsaitaliana.it/borsa/azioni/scheda/IT0003487029.html?lang=it", "http://www.borsaitaliana.it/borsa/azioni/analisi-tecnica.html?isin=IT0003487029&lang=it", "http://finanza-mercati.ilsole24ore.com/quotazioni.php?QUOTE=!UBI.MI", "http://finanza-mercati.ilsole24ore.com/fcxp?page=Dettaglio_FTA_Sommario&cmd=framexplane&chId=70&FILTER_VALUE=IT0003487029&Lettera=U&QUOTE=%21UBI.MI", "http://www.soldionline.it/quotazioni/azioni/IT0003487029.html", "https://finanza.repubblica.it/Company/Advanced?symbol=UBI:IM", "https://it.investing.com/equities/ubi-banca", "", "https://www.milanofinanza.it/quotazioni/dettaglio/ubi-banca-2ae039f", "https://www.milanofinanza.it/mercati/analisi-tecnica?mercato=italiano&stockcodert=039f&codicestrumento=w2ae&DBCOD=UBI"],
  [ "IT0005239360", "http://www.borsaitaliana.it/borsa/azioni/scheda/IT0005239360.html?lang=it", "http://www.borsaitaliana.it/borsa/azioni/analisi-tecnica.html?isin=IT0005239360&lang=it", "http://finanza-mercati.ilsole24ore.com/quotazioni.php?QUOTE=!UCG.MI", "http://finanza-mercati.ilsole24ore.com/fcxp?page=Dettaglio_FTA_Sommario&cmd=framexplane&chId=70&FILTER_VALUE=IT0005239360&Lettera=U&QUOTE=%21UCG.MI", "http://www.soldionline.it/quotazioni/azioni/IT0005239360.html", "https://finanza.repubblica.it/Company/Advanced?symbol=UCG:IM", "https://it.investing.com/equities/unicredito", "", "https://www.milanofinanza.it/quotazioni/dettaglio/unicredit-2ae0096", "https://www.milanofinanza.it/mercati/analisi-tecnica?mercato=italiano&stockcodert=0096&codicestrumento=w2ae&DBCOD=UCG"],
  [ "IT0004810054", "http://www.borsaitaliana.it/borsa/azioni/scheda/IT0004810054.html?lang=it", "http://www.borsaitaliana.it/borsa/azioni/analisi-tecnica.html?isin=IT0004810054&lang=it", "http://finanza-mercati.ilsole24ore.com/quotazioni.php?QUOTE=!UNI.MI", "http://finanza-mercati.ilsole24ore.com/fcxp?page=Dettaglio_FTA_Sommario&cmd=framexplane&chId=70&FILTER_VALUE=IT0004810054&Lettera=U&QUOTE=%21UNI.MI", "http://www.soldionline.it/quotazioni/azioni/IT0004810054.html", "https://finanza.repubblica.it/Company/Advanced?symbol=UNI:IM", "https://it.investing.com/equities/unipol", "", "https://www.milanofinanza.it/quotazioni/dettaglio/unipol-2ae002b", "https://www.milanofinanza.it/mercati/analisi-tecnica?mercato=italiano&stockcodert=002b&codicestrumento=w2ae&DBCOD=UNI"],
  [ "IT0004827447", "http://www.borsaitaliana.it/borsa/azioni/scheda/IT0004827447.html?lang=it", "http://www.borsaitaliana.it/borsa/azioni/analisi-tecnica.html?isin=IT0004827447&lang=it", "http://finanza-mercati.ilsole24ore.com/quotazioni.php?QUOTE=!US.MI", "http://finanza-mercati.ilsole24ore.com/fcxp?page=Dettaglio_FTA_Sommario&cmd=framexplane&chId=70&FILTER_VALUE=IT0004827447&Lettera=U&QUOTE=%21US.MI", "http://www.soldionline.it/quotazioni/azioni/IT0004827447.html", "https://finanza.repubblica.it/Company/Advanced?symbol=US:IM", "https://it.investing.com/equities/fondiaria-sai", "", "https://www.milanofinanza.it/quotazioni/dettaglio/unipolsai-2ae0126", "https://www.milanofinanza.it/mercati/analisi-tecnica?mercato=italiano&stockcodert=0126&codicestrumento=w2ae&DBCOD=US"],
  [ "IT0003540470", "http://www.borsaitaliana.it/borsa/azioni/scheda/IT0003540470.html?lang=it", "http://www.borsaitaliana.it/borsa/azioni/analisi-tecnica.html?isin=IT0003540470&lang=it", "http://finanza-mercati.ilsole24ore.com/quotazioni.php?QUOTE=!YNAP.MI", "http://finanza-mercati.ilsole24ore.com/fcxp?page=Dettaglio_FTA_Sommario&cmd=framexplane&chId=70&FILTER_VALUE=IT0003540470&Lettera=Y&QUOTE=%21YNAP.MI", "http://www.soldionline.it/quotazioni/azioni/IT0003540470.html", "https://finanza.repubblica.it/Company/Advanced?symbol=YNAP:IM", "https://it.investing.com/equities/yoox-spa", "", "https://www.milanofinanza.it/quotazioni/dettaglio/yoox-net-a-porter-group-2ae06a0", "https://www.milanofinanza.it/mercati/analisi-tecnica?mercato=italiano&stockcodert=06a0&codicestrumento=w2ae&DBCOD=YNAP"],
  
  [ "IT0001207098", "http://www.borsaitaliana.it/borsa/azioni/scheda/IT0001207098.html?lang=it", "http://www.borsaitaliana.it/borsa/azioni/analisi-tecnica.html?isin=IT0001207098&lang=it", "http://finanza-mercati.ilsole24ore.com/quotazioni.php?QUOTE=!ACE.MI", "http://finanza-mercati.ilsole24ore.com/fcxp?page=Dettaglio_FTA_Sommario&cmd=framexplane&chId=70&FILTER_VALUE=IT0001207098&Lettera=A&QUOTE=%21ACE.MI", "http://www.soldionline.it/quotazioni/azioni/IT0001207098.html", "https://finanza.repubblica.it/Company/Advanced?symbol=ACE:IM", "https://it.investing.com/equities/acea", "", "https://www.milanofinanza.it/quotazioni/dettaglio/acea-2ae00f8", "https://www.milanofinanza.it/mercati/analisi-tecnica?mercato=italiano&stockcodert=00f8&codicestrumento=w2ae&DBCOD=ACE"],
  [ "IT0001469953", "http://www.borsaitaliana.it/borsa/azioni/scheda/IT0001469953.html?lang=it", "http://www.borsaitaliana.it/borsa/azioni/analisi-tecnica.html?isin=IT0001469953&lang=it", "http://finanza-mercati.ilsole24ore.com/quotazioni.php?QUOTE=!ACO.MI", "http://finanza-mercati.ilsole24ore.com/fcxp?page=Dettaglio_FTA_Sommario&cmd=framexplane&chId=70&FILTER_VALUE=IT0001469953&Lettera=A&QUOTE=%21ACO.MI", "http://www.soldionline.it/quotazioni/azioni/IT0001469953.html", "https://finanza.repubblica.it/Company/Advanced?symbol=ACO:IM", "https://it.investing.com/equities/acotel-group", "", "https://www.milanofinanza.it/quotazioni/dettaglio/acotel-group-2ae0176", "https://www.milanofinanza.it/mercati/analisi-tecnica?mercato=italiano&stockcodert=0176&codicestrumento=w2ae&DBCOD=ACO"],
  [ "IT0001382024", "http://www.borsaitaliana.it/borsa/azioni/scheda/IT0001382024.html?lang=it", "http://www.borsaitaliana.it/borsa/azioni/analisi-tecnica.html?isin=IT0001382024&lang=it", "http://finanza-mercati.ilsole24ore.com/quotazioni.php?QUOTE=!ACS.MI", "http://finanza-mercati.ilsole24ore.com/fcxp?page=Dettaglio_FTA_Sommario&cmd=framexplane&chId=70&FILTER_VALUE=IT0001382024&Lettera=A&QUOTE=%21ACS.MI", "http://www.soldionline.it/quotazioni/azioni/IT0001382024.html", "https://finanza.repubblica.it/Company/Advanced?symbol=ACS:IM", "https://it.investing.com/equities/acsm-agam-spa", "", "https://www.milanofinanza.it/quotazioni/dettaglio/acsm-agam-2ae006a", "https://www.milanofinanza.it/mercati/analisi-tecnica?mercato=italiano&stockcodert=006a&codicestrumento=w2ae&DBCOD=ACS"],
  [ "IT0005065849", "http://www.borsaitaliana.it/borsa/azioni/scheda/IT0005065849.html?lang=it", "http://www.borsaitaliana.it/borsa/azioni/analisi-tecnica.html?isin=IT0005065849&lang=it", "http://finanza-mercati.ilsole24ore.com/quotazioni.php?QUOTE=!AE.MI", "http://finanza-mercati.ilsole24ore.com/fcxp?page=Dettaglio_FTA_Sommario&cmd=framexplane&chId=70&FILTER_VALUE=IT0005065849&Lettera=A&QUOTE=%21AE.MI", "http://www.soldionline.it/quotazioni/azioni/IT0005065849.html", "https://finanza.repubblica.it/Company/Advanced?symbol=AE:IM", "https://it.investing.com/equities/aedes", "", "https://www.milanofinanza.it/quotazioni/dettaglio/aedes-2ae0040", "https://www.milanofinanza.it/mercati/analisi-tecnica?mercato=italiano&stockcodert=0040&codicestrumento=w2ae&DBCOD=AE"],
  [ "IT0001384590", "http://www.borsaitaliana.it/borsa/azioni/scheda/IT0001384590.html?lang=it", "http://www.borsaitaliana.it/borsa/azioni/analisi-tecnica.html?isin=IT0001384590&lang=it", "http://finanza-mercati.ilsole24ore.com/quotazioni.php?QUOTE=!AEF.MI", "http://finanza-mercati.ilsole24ore.com/fcxp?page=Dettaglio_FTA_Sommario&cmd=framexplane&chId=70&FILTER_VALUE=IT0001384590&Lettera=A&QUOTE=%21AEF.MI", "http://www.soldionline.it/quotazioni/azioni/IT0001384590.html", "https://finanza.repubblica.it/Company/Advanced?symbol=AEF:IM", "https://it.investing.com/equities/aeffe-spa", "", "https://www.milanofinanza.it/quotazioni/dettaglio/aeffe-2ae0442", "https://www.milanofinanza.it/mercati/analisi-tecnica?mercato=italiano&stockcodert=0442&codicestrumento=w2ae&DBCOD=AEF"],
  [ "IT0001006128", "http://www.borsaitaliana.it/borsa/azioni/scheda/IT0001006128.html?lang=it", "http://www.borsaitaliana.it/borsa/azioni/analisi-tecnica.html?isin=IT0001006128&lang=it", "http://finanza-mercati.ilsole24ore.com/quotazioni.php?QUOTE=!ADB.MI", "http://finanza-mercati.ilsole24ore.com/fcxp?page=Dettaglio_FTA_Sommario&cmd=framexplane&chId=70&FILTER_VALUE=IT0001006128&Lettera=A&QUOTE=%21ADB.MI", "http://www.soldionline.it/quotazioni/azioni/IT0001006128.html", "https://finanza.repubblica.it/Company/Advanced?symbol=ADB:IM", "https://it.investing.com/equities/aeroporto-guglielmo-marconi-di-bolo", "", "https://www.milanofinanza.it/quotazioni/dettaglio/aeroporto-guglielmo-marconi-di-bologna-2ae105e", "https://www.milanofinanza.it/mercati/analisi-tecnica?mercato=italiano&stockcodert=105e&codicestrumento=w2ae&DBCOD=ADB"],
  [ "IT0004720733", "http://www.borsaitaliana.it/borsa/azioni/scheda/IT0004720733.html?lang=it", "http://www.borsaitaliana.it/borsa/azioni/analisi-tecnica.html?isin=IT0004720733&lang=it", "http://finanza-mercati.ilsole24ore.com/quotazioni.php?QUOTE=!ARN.MI", "http://finanza-mercati.ilsole24ore.com/fcxp?page=Dettaglio_FTA_Sommario&cmd=framexplane&chId=70&FILTER_VALUE=IT0004720733&Lettera=A&QUOTE=%21ARN.MI", "http://www.soldionline.it/quotazioni/azioni/IT0004720733.html", "https://finanza.repubblica.it/Company/Advanced?symbol=ARN:IM", "https://it.investing.com/equities/alerion-clean-power-spa", "", "https://www.milanofinanza.it/quotazioni/dettaglio/alerion-2ae00c2", "https://www.milanofinanza.it/mercati/analisi-tecnica?mercato=italiano&stockcodert=00c2&codicestrumento=w2ae&DBCOD=ARN"],
  [ "IT0001042297", "http://www.borsaitaliana.it/borsa/azioni/scheda/IT0001042297.html?lang=it", "http://www.borsaitaliana.it/borsa/azioni/analisi-tecnica.html?isin=IT0001042297&lang=it", "http://finanza-mercati.ilsole24ore.com/quotazioni.php?QUOTE=!ATH.MI", "http://finanza-mercati.ilsole24ore.com/fcxp?page=Dettaglio_FTA_Sommario&cmd=framexplane&chId=70&FILTER_VALUE=IT0001042297&Lettera=A&QUOTE=%21ATH.MI", "http://www.soldionline.it/quotazioni/azioni/IT0001042297.html", "https://finanza.repubblica.it/Company/Advanced?symbol=ATH:IM", "https://it.investing.com/equities/ambienthesis", "", "https://www.milanofinanza.it/quotazioni/dettaglio/ambienthesis-2ae0035", "https://www.milanofinanza.it/mercati/analisi-tecnica?mercato=italiano&stockcodert=0035&codicestrumento=w2ae&DBCOD=ATH"],
  [ "IT0004056880", "http://www.borsaitaliana.it/borsa/azioni/scheda/IT0004056880.html?lang=it", "http://www.borsaitaliana.it/borsa/azioni/analisi-tecnica.html?isin=IT0004056880&lang=it", "http://finanza-mercati.ilsole24ore.com/quotazioni.php?QUOTE=!AMP.MI", "http://finanza-mercati.ilsole24ore.com/fcxp?page=Dettaglio_FTA_Sommario&cmd=framexplane&chId=70&FILTER_VALUE=IT0004056880&Lettera=A&QUOTE=%21AMP.MI", "http://www.soldionline.it/quotazioni/azioni/IT0004056880.html", "https://finanza.repubblica.it/Company/Advanced?symbol=AMP:IM", "https://it.investing.com/equities/amplifon", "", "https://www.milanofinanza.it/quotazioni/dettaglio/amplifon-2ae01ef", "https://www.milanofinanza.it/mercati/analisi-tecnica?mercato=italiano&stockcodert=01ef&codicestrumento=w2ae&DBCOD=AMP"],
  [ "IT0004998065", "http://www.borsaitaliana.it/borsa/azioni/scheda/IT0004998065.html?lang=it", "http://www.borsaitaliana.it/borsa/azioni/analisi-tecnica.html?isin=IT0004998065&lang=it", "http://finanza-mercati.ilsole24ore.com/quotazioni.php?QUOTE=!ANIM.MI", "http://finanza-mercati.ilsole24ore.com/fcxp?page=Dettaglio_FTA_Sommario&cmd=framexplane&chId=70&FILTER_VALUE=IT0004998065&Lettera=A&QUOTE=%21ANIM.MI", "http://www.soldionline.it/quotazioni/azioni/IT0004998065.html", "https://finanza.repubblica.it/Company/Advanced?symbol=ANIM:IM", "https://it.investing.com/equities/anima-holding-spa", "", "https://www.milanofinanza.it/quotazioni/dettaglio/anima-holding-2ae1035", "https://www.milanofinanza.it/mercati/analisi-tecnica?mercato=italiano&stockcodert=1035&codicestrumento=w2ae&DBCOD=ANIM"],
  [ "IT0003977540", "http://www.borsaitaliana.it/borsa/azioni/scheda/IT0003977540.html?lang=it", "http://www.borsaitaliana.it/borsa/azioni/analisi-tecnica.html?isin=IT0003977540&lang=it", "http://finanza-mercati.ilsole24ore.com/quotazioni.php?QUOTE=!STS.MI", "http://finanza-mercati.ilsole24ore.com/fcxp?page=Dettaglio_FTA_Sommario&cmd=framexplane&chId=70&FILTER_VALUE=IT0003977540&Lettera=A&QUOTE=%21STS.MI", "http://www.soldionline.it/quotazioni/azioni/IT0003977540.html", "https://finanza.repubblica.it/Company/Advanced?symbol=STS:IM", "https://it.investing.com/equities/ansaldo-sts", "", "https://www.milanofinanza.it/quotazioni/dettaglio/ansaldo-sts-2ae03ea", "https://www.milanofinanza.it/mercati/analisi-tecnica?mercato=italiano&stockcodert=03ea&codicestrumento=w2ae&DBCOD=STS"],
  [ "IT0004093263", "http://www.borsaitaliana.it/borsa/azioni/scheda/IT0004093263.html?lang=it", "http://www.borsaitaliana.it/borsa/azioni/analisi-tecnica.html?isin=IT0004093263&lang=it", "http://finanza-mercati.ilsole24ore.com/quotazioni.php?QUOTE=!ASC.MI", "http://finanza-mercati.ilsole24ore.com/fcxp?page=Dettaglio_FTA_Sommario&cmd=framexplane&chId=70&FILTER_VALUE=IT0004093263&Lettera=A&QUOTE=%21ASC.MI", "http://www.soldionline.it/quotazioni/azioni/IT0004093263.html", "https://finanza.repubblica.it/Company/Advanced?symbol=ASC:IM", "https://it.investing.com/equities/ascopiave", "", "https://www.milanofinanza.it/quotazioni/dettaglio/ascopiave-2ae040c", "https://www.milanofinanza.it/mercati/analisi-tecnica?mercato=italiano&stockcodert=040c&codicestrumento=w2ae&DBCOD=ASC"],
  [ "IT0003261069", "http://www.borsaitaliana.it/borsa/azioni/scheda/IT0003261069.html?lang=it", "http://www.borsaitaliana.it/borsa/azioni/analisi-tecnica.html?isin=IT0003261069&lang=it", "http://finanza-mercati.ilsole24ore.com/quotazioni.php?QUOTE=!AST.MI", "http://finanza-mercati.ilsole24ore.com/fcxp?page=Dettaglio_FTA_Sommario&cmd=framexplane&chId=70&FILTER_VALUE=IT0003261069&Lettera=A&QUOTE=%21AST.MI", "http://www.soldionline.it/quotazioni/azioni/IT0003261069.html", "https://finanza.repubblica.it/Company/Advanced?symbol=AST:IM", "https://it.investing.com/equities/astaldi", "", "https://www.milanofinanza.it/quotazioni/dettaglio/astaldi-2ae0370", "https://www.milanofinanza.it/mercati/analisi-tecnica?mercato=italiano&stockcodert=0370&codicestrumento=w2ae&DBCOD=AST"],
  [ "IT0000084027", "http://www.borsaitaliana.it/borsa/azioni/scheda/IT0000084027.html?lang=it", "http://www.borsaitaliana.it/borsa/azioni/analisi-tecnica.html?isin=IT0000084027&lang=it", "http://finanza-mercati.ilsole24ore.com/quotazioni.php?QUOTE=!AT.MI", "http://finanza-mercati.ilsole24ore.com/fcxp?page=Dettaglio_FTA_Sommario&cmd=framexplane&chId=70&FILTER_VALUE=IT0000084027&Lettera=A&QUOTE=%21AT.MI", "http://www.soldionline.it/quotazioni/azioni/IT0000084027.html", "https://finanza.repubblica.it/Company/Advanced?symbol=AT:IM", "https://it.investing.com/equities/autostrada-torino-milano", "", "https://www.milanofinanza.it/quotazioni/dettaglio/astm-2ae004a", "https://www.milanofinanza.it/mercati/analisi-tecnica?mercato=italiano&stockcodert=004a&codicestrumento=w2ae&DBCOD=AT"],
  [ "IT0001137345", "http://www.borsaitaliana.it/borsa/azioni/scheda/IT0001137345.html?lang=it", "http://www.borsaitaliana.it/borsa/azioni/analisi-tecnica.html?isin=IT0001137345&lang=it", "http://finanza-mercati.ilsole24ore.com/quotazioni.php?QUOTE=!AGL.MI", "http://finanza-mercati.ilsole24ore.com/fcxp?page=Dettaglio_FTA_Sommario&cmd=framexplane&chId=70&FILTER_VALUE=IT0001137345&Lettera=A&QUOTE=%21AGL.MI", "http://www.soldionline.it/quotazioni/azioni/IT0001137345.html", "https://finanza.repubblica.it/Company/Advanced?symbol=AGL:IM", "https://it.investing.com/equities/autogrill", "", "https://www.milanofinanza.it/quotazioni/dettaglio/autogrill-spa-2ae00a6", "https://www.milanofinanza.it/mercati/analisi-tecnica?mercato=italiano&stockcodert=00a6&codicestrumento=w2ae&DBCOD=AGL"],
  [ "IT0000084043", "http://www.borsaitaliana.it/borsa/azioni/scheda/IT0000084043.html?lang=it", "http://www.borsaitaliana.it/borsa/azioni/analisi-tecnica.html?isin=IT0000084043&lang=it", "http://finanza-mercati.ilsole24ore.com/quotazioni.php?QUOTE=!AUTME.MI", "http://finanza-mercati.ilsole24ore.com/fcxp?page=Dettaglio_FTA_Sommario&cmd=framexplane&chId=70&FILTER_VALUE=IT0000084043&Lettera=A&QUOTE=%21AUTME.MI", "http://www.soldionline.it/quotazioni/azioni/IT0000084043.html", "https://finanza.repubblica.it/Company/Advanced?symbol=AUTME:IM", "https://it.investing.com/equities/autostrade-meridionali-spa", "", "https://www.milanofinanza.it/quotazioni/dettaglio/autostrade-merid-2ae004d", "https://www.milanofinanza.it/mercati/analisi-tecnica?mercato=italiano&stockcodert=004d&codicestrumento=w2ae&DBCOD=AUTME"],
  [ "IT0005119810", "http://www.borsaitaliana.it/borsa/azioni/scheda/IT0005119810.html?lang=it", "http://www.borsaitaliana.it/borsa/azioni/analisi-tecnica.html?isin=IT0005119810&lang=it", "http://finanza-mercati.ilsole24ore.com/quotazioni.php?QUOTE=!AVIO.MI", "http://finanza-mercati.ilsole24ore.com/fcxp?page=Dettaglio_FTA_Sommario&cmd=framexplane&chId=70&FILTER_VALUE=IT0005119810&Lettera=A&QUOTE=%21AVIO.MI", "http://www.soldionline.it/quotazioni/azioni/IT0005119810.html", "https://finanza.repubblica.it/Company/Advanced?symbol=AVIO:IM", "https://it.investing.com/equities/space2-spa", "", "https://www.milanofinanza.it/quotazioni/dettaglio/avio-2ae1060", "https://www.milanofinanza.it/mercati/analisi-tecnica?mercato=italiano&stockcodert=1060&codicestrumento=w2ae&DBCOD=AVIO"],
    
  [ "IT0001268561", "http://www.borsaitaliana.it/borsa/azioni/scheda/IT0001268561.html?lang=it", "http://www.borsaitaliana.it/borsa/azioni/analisi-tecnica.html?isin=IT0001268561&lang=it", "http://finanza-mercati.ilsole24ore.com/quotazioni.php?QUOTE=!BEC.MI", "http://finanza-mercati.ilsole24ore.com/fcxp?page=Dettaglio_FTA_Sommario&cmd=framexplane&chId=70&FILTER_VALUE=IT0001268561&Lettera=B&QUOTE=%21BEC.MI", "http://www.soldionline.it/quotazioni/azioni/IT0001268561.html", "https://finanza.repubblica.it/Company/Advanced?symbol=BEC:IM", "https://it.investing.com/equities/b---c-speakers-spa", "https://finanza.repubblica.it/Company/?symbol=BEC:IM", "https://www.milanofinanza.it/quotazioni/dettaglio/b-c-speakers-2ae0444", "https://www.milanofinanza.it/mercati/analisi-tecnica?mercato=italiano&stockcodert=0444&codicestrumento=w2ae&DBCOD=BEC"],
  [ "IT0005108763", "http://www.borsaitaliana.it/borsa/azioni/scheda/IT0005108763.html?lang=it", "http://www.borsaitaliana.it/borsa/azioni/analisi-tecnica.html?isin=IT0005108763&lang=it", "http://finanza-mercati.ilsole24ore.com/quotazioni.php?QUOTE=!CRG.MI", "http://finanza-mercati.ilsole24ore.com/fcxp?page=Dettaglio_FTA_Sommario&cmd=framexplane&chId=70&FILTER_VALUE=IT0005108763&Lettera=B&QUOTE=%21CRG.MI", "http://www.soldionline.it/quotazioni/azioni/IT0005108763.html", "https://finanza.repubblica.it/Company/Advanced?symbol=CRG:IM", "https://it.investing.com/equities/banca-carige-spa", "https://finanza.repubblica.it/Company/?symbol=CRG:IM", "https://www.milanofinanza.it/quotazioni/dettaglio/bca-carige-2ae0002", "https://www.milanofinanza.it/mercati/analisi-tecnica?mercato=italiano&stockcodert=0002&codicestrumento=w2ae&DBCOD=CRG"],
  [ "IT0005244402", "http://www.borsaitaliana.it/borsa/azioni/scheda/IT0005244402.html?lang=it", "http://www.borsaitaliana.it/borsa/azioni/analisi-tecnica.html?isin=IT0005244402&lang=it", "http://finanza-mercati.ilsole24ore.com/quotazioni.php?QUOTE=!BFF.MI", "http://finanza-mercati.ilsole24ore.com/fcxp?page=Dettaglio_FTA_Sommario&cmd=framexplane&chId=70&FILTER_VALUE=IT0005244402&Lettera=B&QUOTE=%21BFF.MI", "http://www.soldionline.it/quotazioni/azioni/IT0005244402.html", "https://finanza.repubblica.it/Company/Advanced?symbol=BFF:IM", "https://it.investing.com/equities/banca-farmafactoring-spa", "https://finanza.repubblica.it/Company/?symbol=BFF:IM", "https://www.milanofinanza.it/quotazioni/dettaglio/banca-farmafactoring-2ae10a9", "https://www.milanofinanza.it/mercati/analisi-tecnica?mercato=italiano&stockcodert=10a9&codicestrumento=w2ae&DBCOD=BFF"],
  [ "IT0000088853", "http://www.borsaitaliana.it/borsa/azioni/scheda/IT0000088853.html?lang=it", "http://www.borsaitaliana.it/borsa/azioni/analisi-tecnica.html?isin=IT0000088853&lang=it", "http://finanza-mercati.ilsole24ore.com/quotazioni.php?QUOTE=!BFE.MI", "http://finanza-mercati.ilsole24ore.com/fcxp?page=Dettaglio_FTA_Sommario&cmd=framexplane&chId=70&FILTER_VALUE=IT0000088853&Lettera=B&QUOTE=%21BFE.MI", "http://www.soldionline.it/quotazioni/azioni/IT0000088853.html", "https://finanza.repubblica.it/Company/Advanced?symbol=BFE:IM", "https://it.investing.com/equities/banca-finnat-euramerica-spa", "https://finanza.repubblica.it/Company/?symbol=BFE:IM", "https://www.milanofinanza.it/quotazioni/dettaglio/bca-finnat-2ae019d", "https://www.milanofinanza.it/mercati/analisi-tecnica?mercato=italiano&stockcodert=019d&codicestrumento=w2ae&DBCOD=BFE"],
  [ "IT0003188064", "http://www.borsaitaliana.it/borsa/azioni/scheda/IT0003188064.html?lang=it", "http://www.borsaitaliana.it/borsa/azioni/analisi-tecnica.html?isin=IT0003188064&lang=it", "http://finanza-mercati.ilsole24ore.com/quotazioni.php?QUOTE=!IF.MI", "http://finanza-mercati.ilsole24ore.com/fcxp?page=Dettaglio_FTA_Sommario&cmd=framexplane&chId=70&FILTER_VALUE=IT0003188064&Lettera=B&QUOTE=%21IF.MI", "http://www.soldionline.it/quotazioni/azioni/IT0003188064.html", "https://finanza.repubblica.it/Company/Advanced?symbol=IF:IM", "https://it.investing.com/equities/banca-ifis-spa", "https://finanza.repubblica.it/Company/?symbol=IF:IM", "https://www.milanofinanza.it/quotazioni/dettaglio/banca-ifis-2ae035e", "https://www.milanofinanza.it/mercati/analisi-tecnica?mercato=italiano&stockcodert=035e&codicestrumento=w2ae&DBCOD=IF"],
  [ "IT0000074077", "http://www.borsaitaliana.it/borsa/azioni/scheda/IT0000074077.html?lang=it", "http://www.borsaitaliana.it/borsa/azioni/analisi-tecnica.html?isin=IT0000074077&lang=it", "http://finanza-mercati.ilsole24ore.com/quotazioni.php?QUOTE=!BIM.MI", "http://finanza-mercati.ilsole24ore.com/fcxp?page=Dettaglio_FTA_Sommario&cmd=framexplane&chId=70&FILTER_VALUE=IT0000074077&Lettera=B&QUOTE=%21BIM.MI", "http://www.soldionline.it/quotazioni/azioni/IT0000074077.html", "https://finanza.repubblica.it/Company/Advanced?symbol=BIM:IM", "https://it.investing.com/equities/banca-intermobiliare", "https://finanza.repubblica.it/Company/?symbol=BIM:IM", "https://www.milanofinanza.it/quotazioni/dettaglio/banca-intermobiliare-2ae0101", "https://www.milanofinanza.it/mercati/analisi-tecnica?mercato=italiano&stockcodert=0101&codicestrumento=w2ae&DBCOD=BIM"],
  [ "IT0000784196", "http://www.borsaitaliana.it/borsa/azioni/scheda/IT0000784196.html?lang=it", "http://www.borsaitaliana.it/borsa/azioni/analisi-tecnica.html?isin=IT0000784196&lang=it", "http://finanza-mercati.ilsole24ore.com/quotazioni.php?QUOTE=!BPSO.MI", "http://finanza-mercati.ilsole24ore.com/fcxp?page=Dettaglio_FTA_Sommario&cmd=framexplane&chId=70&FILTER_VALUE=IT0000784196&Lettera=B&QUOTE=%21BPSO.MI", "http://www.soldionline.it/quotazioni/azioni/IT0000784196.html", "https://finanza.repubblica.it/Company/Advanced?symbol=BPSO:IM", "https://it.investing.com/equities/banca-popolare-di-sondrio?cid=48556", "https://finanza.repubblica.it/Company/?symbol=BPSO:IM", "https://www.milanofinanza.it/quotazioni/dettaglio/bca-pop-sondrio-2ae0071", "https://www.milanofinanza.it/mercati/analisi-tecnica?mercato=italiano&stockcodert=0071&codicestrumento=w2ae&DBCOD=BPSO"],
  [ "IT0001073045", "http://www.borsaitaliana.it/borsa/azioni/scheda/IT0001073045.html?lang=it", "http://www.borsaitaliana.it/borsa/azioni/analisi-tecnica.html?isin=IT0001073045&lang=it", "http://finanza-mercati.ilsole24ore.com/quotazioni.php?QUOTE=!PRO.MI", "http://finanza-mercati.ilsole24ore.com/fcxp?page=Dettaglio_FTA_Sommario&cmd=framexplane&chId=70&FILTER_VALUE=IT0001073045&Lettera=B&QUOTE=%21PRO.MI", "http://www.soldionline.it/quotazioni/azioni/IT0001073045.html", "https://finanza.repubblica.it/Company/Advanced?symbol=PRO:IM", "https://it.investing.com/equities/banca-profilo", "https://finanza.repubblica.it/Company/?symbol=PRO:IM", "https://www.milanofinanza.it/quotazioni/dettaglio/bca-profilo-2ae0112", "https://www.milanofinanza.it/mercati/analisi-tecnica?mercato=italiano&stockcodert=0112&codicestrumento=w2ae&DBCOD=PRO"],
  [ "IT0003173629", "http://www.borsaitaliana.it/borsa/azioni/scheda/IT0003173629.html?lang=it", "http://www.borsaitaliana.it/borsa/azioni/analisi-tecnica.html?isin=IT0003173629&lang=it", "http://finanza-mercati.ilsole24ore.com/quotazioni.php?QUOTE=!BST.MI", "http://finanza-mercati.ilsole24ore.com/fcxp?page=Dettaglio_FTA_Sommario&cmd=framexplane&chId=70&FILTER_VALUE=IT0003173629&Lettera=B&QUOTE=%21BST.MI", "http://www.soldionline.it/quotazioni/azioni/IT0003173629.html", "https://finanza.repubblica.it/Company/Advanced?symbol=BST:IM", "https://it.investing.com/equities/banca-sistema-spa", "https://finanza.repubblica.it/Company/?symbol=BST:IM", "https://www.milanofinanza.it/quotazioni/dettaglio/banca-sistema-2ae105c", "https://www.milanofinanza.it/mercati/analisi-tecnica?mercato=italiano&stockcodert=105c&codicestrumento=w2ae&DBCOD=BST"],
  [ "IT0001041000", "http://www.borsaitaliana.it/borsa/azioni/scheda/IT0001041000.html?lang=it", "http://www.borsaitaliana.it/borsa/azioni/analisi-tecnica.html?isin=IT0001041000&lang=it", "http://finanza-mercati.ilsole24ore.com/quotazioni.php?QUOTE=!BDB.MI", "http://finanza-mercati.ilsole24ore.com/fcxp?page=Dettaglio_FTA_Sommario&cmd=framexplane&chId=70&FILTER_VALUE=IT0001041000&Lettera=B&QUOTE=%21BDB.MI", "http://www.soldionline.it/quotazioni/azioni/IT0001041000.html", "https://finanza.repubblica.it/Company/Advanced?symbol=BDB:IM", "https://it.investing.com/equities/banco-desio-spa", "https://finanza.repubblica.it/Company/?symbol=BDB:IM", "https://www.milanofinanza.it/quotazioni/dettaglio/bco-desio-brianza-2ae0005", "https://www.milanofinanza.it/mercati/analisi-tecnica?mercato=italiano&stockcodert=0005&codicestrumento=w2ae&DBCOD=BDB"],
  [ "IT0001005070", "http://www.borsaitaliana.it/borsa/azioni/scheda/IT0001005070.html?lang=it", "http://www.borsaitaliana.it/borsa/azioni/analisi-tecnica.html?isin=IT0001005070&lang=it", "http://finanza-mercati.ilsole24ore.com/quotazioni.php?QUOTE=!BSRP.MI", "http://finanza-mercati.ilsole24ore.com/fcxp?page=Dettaglio_FTA_Sommario&cmd=framexplane&chId=70&FILTER_VALUE=IT0001005070&Lettera=B&QUOTE=%21BSRP.MI", "http://www.soldionline.it/quotazioni/azioni/IT0001005070.html", "https://finanza.repubblica.it/Company/Advanced?symbol=BSRP:IM", "https://it.investing.com/equities/banco-di-sardegna-spa", "https://finanza.repubblica.it/Company/?symbol=BSRP:IM", "https://www.milanofinanza.it/quotazioni/dettaglio/bco-sardegna-risp-2ae0076", "https://www.milanofinanza.it/mercati/analisi-tecnica?mercato=italiano&stockcodert=0076&codicestrumento=w2ae&DBCOD=BSRP"],
  [ "IT0001033700", "http://www.borsaitaliana.it/borsa/azioni/scheda/IT0001033700.html?lang=it", "http://www.borsaitaliana.it/borsa/azioni/analisi-tecnica.html?isin=IT0001033700&lang=it", "http://finanza-mercati.ilsole24ore.com/quotazioni.php?QUOTE=!BAN.MI", "http://finanza-mercati.ilsole24ore.com/fcxp?page=Dettaglio_FTA_Sommario&cmd=framexplane&chId=70&FILTER_VALUE=IT0001033700&Lettera=B&QUOTE=%21BAN.MI", "http://www.soldionline.it/quotazioni/azioni/IT0001033700.html", "https://finanza.repubblica.it/Company/Advanced?symbol=BAN:IM", "https://it.investing.com/equities/basic-net-spa", "https://finanza.repubblica.it/Company/?symbol=BAN:IM", "https://www.milanofinanza.it/quotazioni/dettaglio/basicnet-2ae00ea", "https://www.milanofinanza.it/mercati/analisi-tecnica?mercato=italiano&stockcodert=00ea&codicestrumento=w2ae&DBCOD=BAN"],
  [ "IT0004412497", "http://www.borsaitaliana.it/borsa/azioni/scheda/IT0004412497.html?lang=it", "http://www.borsaitaliana.it/borsa/azioni/analisi-tecnica.html?isin=IT0004412497&lang=it", "http://finanza-mercati.ilsole24ore.com/quotazioni.php?QUOTE=!B.MI", "http://finanza-mercati.ilsole24ore.com/fcxp?page=Dettaglio_FTA_Sommario&cmd=framexplane&chId=70&FILTER_VALUE=IT0004412497&Lettera=B&QUOTE=%21B.MI", "http://www.soldionline.it/quotazioni/azioni/IT0004412497.html", "https://finanza.repubblica.it/Company/Advanced?symbol=B:IM", "https://it.investing.com/equities/bastogi-spa", "https://finanza.repubblica.it/Company/?symbol=B:IM", "https://www.milanofinanza.it/quotazioni/dettaglio/bastogi-spa-2ae0052", "https://www.milanofinanza.it/mercati/analisi-tecnica?mercato=italiano&stockcodert=0052&codicestrumento=w2ae&DBCOD=B"],
  [ "IT0001479523", "http://www.borsaitaliana.it/borsa/azioni/scheda/IT0001479523.html?lang=it", "http://www.borsaitaliana.it/borsa/azioni/analisi-tecnica.html?isin=IT0001479523&lang=it", "http://finanza-mercati.ilsole24ore.com/quotazioni.php?QUOTE=!BET.MI", "http://finanza-mercati.ilsole24ore.com/fcxp?page=Dettaglio_FTA_Sommario&cmd=framexplane&chId=70&FILTER_VALUE=IT0001479523&Lettera=B&QUOTE=%21BET.MI", "http://www.soldionline.it/quotazioni/azioni/IT0001479523.html", "https://finanza.repubblica.it/Company/Advanced?symbol=BET:IM", "https://it.investing.com/equities/bee-team", "https://finanza.repubblica.it/Company/?symbol=BET:IM", "https://www.milanofinanza.it/quotazioni/dettaglio/be-2ae0476", "https://www.milanofinanza.it/mercati/analisi-tecnica?mercato=italiano&stockcodert=0476&codicestrumento=w2ae&DBCOD=BET"],
  [ "IT0001223277", "http://www.borsaitaliana.it/borsa/azioni/scheda/IT0001223277.html?lang=it", "http://www.borsaitaliana.it/borsa/azioni/analisi-tecnica.html?isin=IT0001223277&lang=it", "http://finanza-mercati.ilsole24ore.com/quotazioni.php?QUOTE=!BE.MI", "http://finanza-mercati.ilsole24ore.com/fcxp?page=Dettaglio_FTA_Sommario&cmd=framexplane&chId=70&FILTER_VALUE=IT0001223277&Lettera=B&QUOTE=%21BE.MI", "http://www.soldionline.it/quotazioni/azioni/IT0001223277.html", "https://finanza.repubblica.it/Company/Advanced?symbol=BE:IM", "https://it.investing.com/equities/beghelli", "https://finanza.repubblica.it/Company/?symbol=BE:IM", "https://www.milanofinanza.it/quotazioni/dettaglio/beghelli-2ae007b", "https://www.milanofinanza.it/mercati/analisi-tecnica?mercato=italiano&stockcodert=007b&codicestrumento=w2ae&DBCOD=BE"],
  [ "IT0001389631", "http://www.borsaitaliana.it/borsa/azioni/scheda/IT0001389631.html?lang=it", "http://www.borsaitaliana.it/borsa/azioni/analisi-tecnica.html?isin=IT0001389631&lang=it", "http://finanza-mercati.ilsole24ore.com/quotazioni.php?QUOTE=!BNS.MI", "http://finanza-mercati.ilsole24ore.com/fcxp?page=Dettaglio_FTA_Sommario&cmd=framexplane&chId=70&FILTER_VALUE=IT0001389631&Lettera=B&QUOTE=%21BNS.MI", "http://www.soldionline.it/quotazioni/azioni/IT0001389631.html", "https://finanza.repubblica.it/Company/Advanced?symbol=BNS:IM", "https://it.investing.com/equities/beni-stabili", "https://finanza.repubblica.it/Company/?symbol=BNS:IM", "https://www.milanofinanza.it/quotazioni/dettaglio/beni-stabili-2ae00aa", "https://www.milanofinanza.it/mercati/analisi-tecnica?mercato=italiano&stockcodert=00aa&codicestrumento=w2ae&DBCOD=BNS"],
  [ "IT0004273915", "http://www.borsaitaliana.it/borsa/azioni/scheda/IT0004273915.html?lang=it", "http://www.borsaitaliana.it/borsa/azioni/analisi-tecnica.html?isin=IT0004273915&lang=it", "http://finanza-mercati.ilsole24ore.com/quotazioni.php?QUOTE=!BEST.MI", "http://finanza-mercati.ilsole24ore.com/fcxp?page=Dettaglio_FTA_Sommario&cmd=framexplane&chId=70&FILTER_VALUE=IT0004273915&Lettera=B&QUOTE=%21BEST.MI", "http://www.soldionline.it/quotazioni/azioni/IT0004273915.html", "https://finanza.repubblica.it/Company/Advanced?symbol=BEST:IM", "https://it.investing.com/equities/best-union-company-spa", "https://finanza.repubblica.it/Company/?symbol=BEST:IM", "https://www.milanofinanza.it/quotazioni/dettaglio/best-union-company-2ae0468", "https://www.milanofinanza.it/mercati/analisi-tecnica?mercato=italiano&stockcodert=0468&codicestrumento=w2ae&DBCOD=BEST"],
  [ "IT0004222102", "http://www.borsaitaliana.it/borsa/azioni/scheda/IT0004222102.html?lang=it", "http://www.borsaitaliana.it/borsa/azioni/analisi-tecnica.html?isin=IT0004222102&lang=it", "http://finanza-mercati.ilsole24ore.com/quotazioni.php?QUOTE=!BIA.MI", "http://finanza-mercati.ilsole24ore.com/fcxp?page=Dettaglio_FTA_Sommario&cmd=framexplane&chId=70&FILTER_VALUE=IT0004222102&Lettera=B&QUOTE=%21BIA.MI", "http://www.soldionline.it/quotazioni/azioni/IT0004222102.html", "https://finanza.repubblica.it/Company/Advanced?symbol=BIO:IM", "https://it.investing.com/equities/bialetti-industrie-spa", "https://finanza.repubblica.it/Company/?symbol=BIA:IM", "https://www.milanofinanza.it/quotazioni/dettaglio/bialetti-industrie-2ae0445", "https://www.milanofinanza.it/mercati/analisi-tecnica?mercato=italiano&stockcodert=0445&codicestrumento=w2ae&DBCOD=BIA"],
  [ "IT0004095888", "http://www.borsaitaliana.it/borsa/azioni/scheda/IT0004095888.html?lang=it", "http://www.borsaitaliana.it/borsa/azioni/analisi-tecnica.html?isin=IT0004095888&lang=it", "http://finanza-mercati.ilsole24ore.com/quotazioni.php?QUOTE=!BCM.MI", "http://finanza-mercati.ilsole24ore.com/fcxp?page=Dettaglio_FTA_Sommario&cmd=framexplane&chId=70&FILTER_VALUE=IT0004095888&Lettera=B&QUOTE=%21BCM.MI", "http://www.soldionline.it/quotazioni/azioni/IT0004095888.html", "https://finanza.repubblica.it/Company/Advanced?symbol=BCM:IM", "https://it.investing.com/equities/biancamano-spa", "https://finanza.repubblica.it/Company/?symbol=BCM:IM", "https://www.milanofinanza.it/quotazioni/dettaglio/biancamano-2ae0415", "https://www.milanofinanza.it/mercati/analisi-tecnica?mercato=italiano&stockcodert=0415&codicestrumento=w2ae&DBCOD=BCM"],
  [ "IT0003097257", "http://www.borsaitaliana.it/borsa/azioni/scheda/IT0003097257.html?lang=it", "http://www.borsaitaliana.it/borsa/azioni/analisi-tecnica.html?isin=IT0003097257&lang=it", "http://finanza-mercati.ilsole24ore.com/quotazioni.php?QUOTE=!BSS.MI", "http://finanza-mercati.ilsole24ore.com/fcxp?page=Dettaglio_FTA_Sommario&cmd=framexplane&chId=70&FILTER_VALUE=IT0003097257&Lettera=B&QUOTE=%21BSS.MI", "http://www.soldionline.it/quotazioni/azioni/IT0003097257.html", "https://finanza.repubblica.it/Company/Advanced?symbol=BSS:IM", "https://it.investing.com/equities/biesse-spa", "https://finanza.repubblica.it/Company/?symbol=BSS:IM", "https://www.milanofinanza.it/quotazioni/dettaglio/biesse-2ae01ed", "https://www.milanofinanza.it/mercati/analisi-tecnica?mercato=italiano&stockcodert=01ed&codicestrumento=w2ae&DBCOD=BSS"],
  [ "IT0004711203", "http://www.borsaitaliana.it/borsa/azioni/scheda/IT0004711203.html?lang=it", "http://www.borsaitaliana.it/borsa/azioni/analisi-tecnica.html?isin=IT0004711203&lang=it", "http://finanza-mercati.ilsole24ore.com/quotazioni.php?QUOTE=!BIE.MI", "http://finanza-mercati.ilsole24ore.com/fcxp?page=Dettaglio_FTA_Sommario&cmd=framexplane&chId=70&FILTER_VALUE=IT0004711203&Lettera=B&QUOTE=%21BIE.MI", "http://www.soldionline.it/quotazioni/azioni/IT0004711203.html", "https://finanza.repubblica.it/Company/Advanced?symbol=BIE:IM", "https://it.investing.com/equities/bioera-spa", "https://finanza.repubblica.it/Company/?symbol=BIE:IM", "https://www.milanofinanza.it/quotazioni/dettaglio/bioera-2ae03d6", "https://www.milanofinanza.it/mercati/analisi-tecnica?mercato=italiano&stockcodert=03d6&codicestrumento=w2ae&DBCOD=BIE"],
  [ "IT0000066180", "http://www.borsaitaliana.it/borsa/azioni/scheda/IT0000066180.html?lang=it", "http://www.borsaitaliana.it/borsa/azioni/analisi-tecnica.html?isin=IT0000066180&lang=it", "http://finanza-mercati.ilsole24ore.com/quotazioni.php?QUOTE=!BRI.MI", "http://finanza-mercati.ilsole24ore.com/fcxp?page=Dettaglio_FTA_Sommario&cmd=framexplane&chId=70&FILTER_VALUE=IT0000066180&Lettera=B&QUOTE=%21BRI.MI", "http://www.soldionline.it/quotazioni/azioni/IT0000066180.html", "https://finanza.repubblica.it/Company/Advanced?symbol=BRI:IM", "https://it.investing.com/equities/brioschi-sviluppo-immobiliare-spa", "https://finanza.repubblica.it/Company/?symbol=BRI:IM", "https://www.milanofinanza.it/quotazioni/dettaglio/brioschi-2ae0072", "https://www.milanofinanza.it/mercati/analisi-tecnica?mercato=italiano&stockcodert=0072&codicestrumento=w2ae&DBCOD=BRI"],
  [ "IT0004764699", "http://www.borsaitaliana.it/borsa/azioni/scheda/IT0004764699.html?lang=it", "http://www.borsaitaliana.it/borsa/azioni/analisi-tecnica.html?isin=IT0004764699&lang=it", "http://finanza-mercati.ilsole24ore.com/quotazioni.php?QUOTE=!BC.MI", "http://finanza-mercati.ilsole24ore.com/fcxp?page=Dettaglio_FTA_Sommario&cmd=framexplane&chId=70&FILTER_VALUE=IT0004764699&Lettera=B&QUOTE=%21BC.MI", "http://www.soldionline.it/quotazioni/azioni/IT0004764699.html", "https://finanza.repubblica.it/Company/Advanced?symbol=BC:IM", "https://it.investing.com/equities/brunello-cucinelli-spa", "https://finanza.repubblica.it/Company/?symbol=BC:IM", "https://www.milanofinanza.it/quotazioni/dettaglio/brunello-cucinelli-2ae1001", "https://www.milanofinanza.it/mercati/analisi-tecnica?mercato=italiano&stockcodert=1001&codicestrumento=w2ae&DBCOD=BC"],
  [ "IT0001347308", "http://www.borsaitaliana.it/borsa/azioni/scheda/IT0001347308.html?lang=it", "http://www.borsaitaliana.it/borsa/azioni/analisi-tecnica.html?isin=IT0001347308&lang=it", "http://finanza-mercati.ilsole24ore.com/quotazioni.php?QUOTE=!BZU.MI", "http://finanza-mercati.ilsole24ore.com/fcxp?page=Dettaglio_FTA_Sommario&cmd=framexplane&chId=70&FILTER_VALUE=IT0001347308&Lettera=B&QUOTE=%21BZU.MI", "http://www.soldionline.it/quotazioni/azioni/IT0001347308.html", "https://finanza.repubblica.it/Company/Advanced?symbol=BZU:IM", "https://it.investing.com/equities/buzzi-unicem", "https://finanza.repubblica.it/Company/?symbol=BZU:IM", "https://www.milanofinanza.it/quotazioni/dettaglio/buzzi-unicem-2ae0013", "https://www.milanofinanza.it/mercati/analisi-tecnica?mercato=italiano&stockcodert=0013&codicestrumento=w2ae&DBCOD=BZU"]
]

url_list.each do |isin, url1, url2, url3, url4, url5, url6, url7, url8, url9, url10|
  Url.create(isin: isin, url1: url1, url2: url2, url3: url3, url4: url4, url5: url5, url6: url6, url7: url7, url8: url8, url9: url9, url10: url10)
end
###Url###



###Market###
#market_list = [ 
#  [ "FTSE MIB", "", ""],
#  [ "FTSE All Share", "", ""],
#  [ "S&P 100", "", ""],
#  [ "NASDAQ 100", "", ""],
#  [ "DAX 30", "", ""],
#  [ "CAC 40", "", ""],
#  [ "NIKKEI 225", "", ""],
#  [ "GOLD", "", ""],
#  [ "Brent", "", ""],
#  [ "WTI", "", ""],
#  [ "EUR/USD", "", ""],
#  [ "EUR/GBP", "", ""]
#]

#market_list.each do |name, value, variation|
  #Market.create(name: name, value: value, variation: variation)
#end
###Market###



###Analysis###
analysis_list = [
 [1, "IT0001233417", nil, nil, "", nil, nil, "", "", "", "", nil, nil, nil, "", nil],
 [2, "IT0003506190", nil, nil, "", nil, nil, "", "", "", "", nil, nil, nil, "", nil],
 [3, "IT0003261697", nil, nil, "", nil, nil, "", "", "", "", nil, nil, nil, "", nil],
 [4, "IT0001031084", nil, nil, "", nil, nil, "", "", "", "", nil, nil, nil, "", nil],
 [5, "IT0004776628", nil, nil, "", nil, nil, "", "", "", "", nil, nil, nil, "", nil],
 [6, "IT0005218380", nil, nil, "", nil, nil, "", "", "", "", nil, nil, nil, "", nil],
 [7, "IT0000066123", nil, nil, "", nil, nil, "", "", "", "", nil, nil, nil, "", nil],
 [8, "IT0005252728", nil, nil, "", nil, nil, "", "", "", "", nil, nil, nil, "", nil],
 [9, "IT0001347308", nil, nil, "", nil, nil, "", "", "", "", nil, nil, nil, "", nil],
 [10, "IT0005252207", nil, nil, "", nil, nil, "", "", "", "", nil, nil, nil, "", nil],
 [11, "NL0010545661", nil, nil, "", nil, nil, "", "", "", "", nil, nil, nil, "", nil],
 [12, "IT0003128367", nil, nil, "", nil, nil, "", "", "", "", nil, nil, nil, "", nil],
 [13, "IT0003132476", nil, nil, "", nil, nil, "", "", "", "", nil, nil, nil, "", nil],  
 [14, "NL0012059018", nil, nil, "", nil, nil, "", "", "", "", nil, nil, nil, "", nil],
 [15, "NL0011585146", nil, nil, "", nil, nil, "", "", "", "", nil, nil, nil, "", nil],
 [16, "NL0010877643", nil, nil, "", nil, nil, "", "", "", "", nil, nil, nil, "", nil],
 [17, "IT0000072170", nil, nil, "", nil, nil, "", "", "", "", nil, nil, nil, "", nil],
 [18, "IT0000062072", nil, nil, "", nil, nil, "", "", "", "", nil, nil, nil, "", nil],
 [19, "IT0000072618", nil, nil, "", nil, nil, "", "", "", "", nil, nil, nil, "", nil],
 [20, "IT0005211237", nil, nil, "", nil, nil, "", "", "", "", nil, nil, nil, "", nil],
 [21, "IT0003856405", nil, nil, "", nil, nil, "", "", "", "", nil, nil, nil, "", nil],
 [22, "IT0001479374", nil, nil, "", nil, nil, "", "", "", "", nil, nil, nil, "", nil],
 [23, "IT0001063210", nil, nil, "", nil, nil, "", "", "", "", nil, nil, nil, "", nil],  
 [24, "IT0000062957", nil, nil, "", nil, nil, "", "", "", "", nil, nil, nil, "", nil],
 [25, "IT0004965148", nil, nil, "", nil, nil, "", "", "", "", nil, nil, nil, "", nil],
 [26, "IT0003796171", nil, nil, "", nil, nil, "", "", "", "", nil, nil, nil, "", nil],
 [27, "IT0004176001", nil, nil, "", nil, nil, "", "", "", "", nil, nil, nil, "", nil],
 [28, "IT0003828271", nil, nil, "", nil, nil, "", "", "", "", nil, nil, nil, "", nil],
 [29, "IT0005252140", nil, nil, "", nil, nil, "", "", "", "", nil, nil, nil, "", nil],
 [30, "IT0004712375", nil, nil, "", nil, nil, "", "", "", "", nil, nil, nil, "", nil],
 [31, "IT0003153415", nil, nil, "", nil, nil, "", "", "", "", nil, nil, nil, "", nil],
 [32, "NL0000226223", nil, nil, "", nil, nil, "", "", "", "", nil, nil, nil, "", nil],
 [33, "IT0003497168", nil, nil, "", nil, nil, "", "", "", "", nil, nil, nil, "", nil], 
 [34, "LU0156801721", nil, nil, "", nil, nil, "", "", "", "", nil, nil, nil, "", nil],
 [35, "IT0003242622", nil, nil, "", nil, nil, "", "", "", "", nil, nil, nil, "", nil],
 [36, "IT0003487029", nil, nil, "", nil, nil, "", "", "", "", nil, nil, nil, "", nil],
 [37, "IT0005239360", nil, nil, "", nil, nil, "", "", "", "", nil, nil, nil, "", nil],
 [38, "IT0004810054", nil, nil, "", nil, nil, "", "", "", "", nil, nil, nil, "", nil],
 [39, "IT0004827447", nil, nil, "", nil, nil, "", "", "", "", nil, nil, nil, "", nil],
 [40, "IT0003540470", nil, nil, "", nil, nil, "", "", "", "", nil, nil, nil, "", nil],
  
 [41, "IT0001207098", nil, nil, "", nil, nil, "", "", "", "", nil, nil, nil, "", nil],
 [42, "IT0001469953", nil, nil, "", nil, nil, "", "", "", "", nil, nil, nil, "", nil],
 [43, "IT0001382024", nil, nil, "", nil, nil, "", "", "", "", nil, nil, nil, "", nil],
 [44, "IT0005065849", nil, nil, "", nil, nil, "", "", "", "", nil, nil, nil, "", nil],
 [45, "IT0001384590", nil, nil, "", nil, nil, "", "", "", "", nil, nil, nil, "", nil],
 [46, "IT0001006128", nil, nil, "", nil, nil, "", "", "", "", nil, nil, nil, "", nil],
 [47, "IT0004720733", nil, nil, "", nil, nil, "", "", "", "", nil, nil, nil, "", nil],
 [48, "IT0001042297", nil, nil, "", nil, nil, "", "", "", "", nil, nil, nil, "", nil],
 [49, "IT0004056880", nil, nil, "", nil, nil, "", "", "", "", nil, nil, nil, "", nil],
 [50, "IT0004998065", nil, nil, "", nil, nil, "", "", "", "", nil, nil, nil, "", nil],
 [51, "IT0003977540", nil, nil, "", nil, nil, "", "", "", "", nil, nil, nil, "", nil],
 [52, "IT0004093263", nil, nil, "", nil, nil, "", "", "", "", nil, nil, nil, "", nil],
 [53, "IT0003261069", nil, nil, "", nil, nil, "", "", "", "", nil, nil, nil, "", nil],
 [54, "IT0000084027", nil, nil, "", nil, nil, "", "", "", "", nil, nil, nil, "", nil],
 [55, "IT0001137345", nil, nil, "", nil, nil, "", "", "", "", nil, nil, nil, "", nil],
 [56, "IT0000084043", nil, nil, "", nil, nil, "", "", "", "", nil, nil, nil, "", nil],
 [57, "IT0005119810", nil, nil, "", nil, nil, "", "", "", "", nil, nil, nil, "", nil],
 
 [58, "IT0001268561", nil, nil, "", nil, nil, "", "", "", "", nil, nil, nil, "", nil],
 [59, "IT0005108763", nil, nil, "", nil, nil, "", "", "", "", nil, nil, nil, "", nil],
 [60, "IT0005244402", nil, nil, "", nil, nil, "", "", "", "", nil, nil, nil, "", nil],
 [61, "IT0000088853", nil, nil, "", nil, nil, "", "", "", "", nil, nil, nil, "", nil],
 [62, "IT0003188064", nil, nil, "", nil, nil, "", "", "", "", nil, nil, nil, "", nil],
 [63, "IT0000074077", nil, nil, "", nil, nil, "", "", "", "", nil, nil, nil, "", nil],
 [64, "IT0000784196", nil, nil, "", nil, nil, "", "", "", "", nil, nil, nil, "", nil],
 [65, "IT0001073045", nil, nil, "", nil, nil, "", "", "", "", nil, nil, nil, "", nil],
 [66, "IT0003173629", nil, nil, "", nil, nil, "", "", "", "", nil, nil, nil, "", nil],
 [67, "IT0001041000", nil, nil, "", nil, nil, "", "", "", "", nil, nil, nil, "", nil],
 [68, "IT0001005070", nil, nil, "", nil, nil, "", "", "", "", nil, nil, nil, "", nil],
 [69, "IT0001033700", nil, nil, "", nil, nil, "", "", "", "", nil, nil, nil, "", nil],
 [70, "IT0004412497", nil, nil, "", nil, nil, "", "", "", "", nil, nil, nil, "", nil],
 [71, "IT0001479523", nil, nil, "", nil, nil, "", "", "", "", nil, nil, nil, "", nil],
 [72, "IT0001223277", nil, nil, "", nil, nil, "", "", "", "", nil, nil, nil, "", nil],
 [73, "IT0001389631", nil, nil, "", nil, nil, "", "", "", "", nil, nil, nil, "", nil],
 [74, "IT0004273915", nil, nil, "", nil, nil, "", "", "", "", nil, nil, nil, "", nil],
 [75, "IT0004222102", nil, nil, "", nil, nil, "", "", "", "", nil, nil, nil, "", nil],
 [76, "IT0004095888", nil, nil, "", nil, nil, "", "", "", "", nil, nil, nil, "", nil],
 [77, "IT0003097257", nil, nil, "", nil, nil, "", "", "", "", nil, nil, nil, "", nil],
 [78, "IT0004711203", nil, nil, "", nil, nil, "", "", "", "", nil, nil, nil, "", nil],
 [79, "IT0000066180", nil, nil, "", nil, nil, "", "", "", "", nil, nil, nil, "", nil],
 [80, "IT0004764699", nil, nil, "", nil, nil, "", "", "", "", nil, nil, nil, "", nil],
 [81, "IT0001347308", nil, nil, "", nil, nil, "", "", "", "", nil, nil, nil, "", nil]
]

analysis_list.each do |stock_id, isin, borsa_italiana_support, borsa_italiana_resistance, borsa_italiana_fta, xxivore_support, xxivore_resistance, xxivore_shorttrend, xxivore_ftaindex, xxivore_rsi, xxivore_rsidiv, repubblica_support, repubblica_resistance, milano_finanza_risk, milano_finanza_rating, investing_dotcomrating|
  Analysis.create(stock_id: stock_id, isin: isin, borsa_italiana_support: borsa_italiana_support, borsa_italiana_resistance: borsa_italiana_resistance, borsa_italiana_fta: borsa_italiana_fta, xxivore_support: xxivore_support, xxivore_resistance: xxivore_resistance, xxivore_shorttrend: xxivore_shorttrend, xxivore_ftaindex: xxivore_ftaindex, xxivore_rsi: xxivore_rsi, xxivore_rsidiv: xxivore_rsidiv, repubblica_support: repubblica_support, repubblica_resistance: repubblica_resistance, milano_finanza_risk: milano_finanza_risk, milano_finanza_rating: milano_finanza_rating, investing_dotcomrating: investing_dotcomrating)
end
###Analysis setup###



###Study###

###Study###